// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: rep_inferred_input_v1/masked_listings_w_media.proto

package rep_inferred_input_v1

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type MaskedListingsWMediaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GetListings *MaskedListingsWMediaRequest_GetListingsGen `protobuf:"bytes,1,opt,name=get_listings,json=getListings,proto3" json:"get_listings,omitempty"`
}

func (x *MaskedListingsWMediaRequest) Reset() {
	*x = MaskedListingsWMediaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rep_inferred_input_v1_masked_listings_w_media_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MaskedListingsWMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaskedListingsWMediaRequest) ProtoMessage() {}

func (x *MaskedListingsWMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rep_inferred_input_v1_masked_listings_w_media_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaskedListingsWMediaRequest.ProtoReflect.Descriptor instead.
func (*MaskedListingsWMediaRequest) Descriptor() ([]byte, []int) {
	return file_rep_inferred_input_v1_masked_listings_w_media_proto_rawDescGZIP(), []int{0}
}

func (x *MaskedListingsWMediaRequest) GetGetListings() *MaskedListingsWMediaRequest_GetListingsGen {
	if x != nil {
		return x.GetListings
	}
	return nil
}

type MaskedListingsWMediaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Listings []*MaskedListingsWMediaResponse_ListingsGen `protobuf:"bytes,1,rep,name=listings,proto3" json:"listings,omitempty"`
}

func (x *MaskedListingsWMediaResponse) Reset() {
	*x = MaskedListingsWMediaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rep_inferred_input_v1_masked_listings_w_media_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MaskedListingsWMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaskedListingsWMediaResponse) ProtoMessage() {}

func (x *MaskedListingsWMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rep_inferred_input_v1_masked_listings_w_media_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaskedListingsWMediaResponse.ProtoReflect.Descriptor instead.
func (*MaskedListingsWMediaResponse) Descriptor() ([]byte, []int) {
	return file_rep_inferred_input_v1_masked_listings_w_media_proto_rawDescGZIP(), []int{1}
}

func (x *MaskedListingsWMediaResponse) GetListings() []*MaskedListingsWMediaResponse_ListingsGen {
	if x != nil {
		return x.Listings
	}
	return nil
}

type MaskedListingsWMediaRequest_GetListingsGen struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
}

func (x *MaskedListingsWMediaRequest_GetListingsGen) Reset() {
	*x = MaskedListingsWMediaRequest_GetListingsGen{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rep_inferred_input_v1_masked_listings_w_media_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MaskedListingsWMediaRequest_GetListingsGen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaskedListingsWMediaRequest_GetListingsGen) ProtoMessage() {}

func (x *MaskedListingsWMediaRequest_GetListingsGen) ProtoReflect() protoreflect.Message {
	mi := &file_rep_inferred_input_v1_masked_listings_w_media_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaskedListingsWMediaRequest_GetListingsGen.ProtoReflect.Descriptor instead.
func (*MaskedListingsWMediaRequest_GetListingsGen) Descriptor() ([]byte, []int) {
	return file_rep_inferred_input_v1_masked_listings_w_media_proto_rawDescGZIP(), []int{0, 0}
}

func (x *MaskedListingsWMediaRequest_GetListingsGen) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type MaskedListingsWMediaResponse_ListingsGen struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title       string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	PhotoUrl    string `protobuf:"bytes,3,opt,name=photo_url,json=photoUrl,proto3" json:"photo_url,omitempty"`
}

func (x *MaskedListingsWMediaResponse_ListingsGen) Reset() {
	*x = MaskedListingsWMediaResponse_ListingsGen{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rep_inferred_input_v1_masked_listings_w_media_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MaskedListingsWMediaResponse_ListingsGen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaskedListingsWMediaResponse_ListingsGen) ProtoMessage() {}

func (x *MaskedListingsWMediaResponse_ListingsGen) ProtoReflect() protoreflect.Message {
	mi := &file_rep_inferred_input_v1_masked_listings_w_media_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaskedListingsWMediaResponse_ListingsGen.ProtoReflect.Descriptor instead.
func (*MaskedListingsWMediaResponse_ListingsGen) Descriptor() ([]byte, []int) {
	return file_rep_inferred_input_v1_masked_listings_w_media_proto_rawDescGZIP(), []int{1, 0}
}

func (x *MaskedListingsWMediaResponse_ListingsGen) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MaskedListingsWMediaResponse_ListingsGen) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MaskedListingsWMediaResponse_ListingsGen) GetPhotoUrl() string {
	if x != nil {
		return x.PhotoUrl
	}
	return ""
}

var File_rep_inferred_input_v1_masked_listings_w_media_proto protoreflect.FileDescriptor

var file_rep_inferred_input_v1_masked_listings_w_media_proto_rawDesc = []byte{
	0x0a, 0x33, 0x72, 0x65, 0x70, 0x5f, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x72, 0x65, 0x64, 0x5f, 0x69,
	0x6e, 0x70, 0x75, 0x74, 0x5f, 0x76, 0x31, 0x2f, 0x6d, 0x61, 0x73, 0x6b, 0x65, 0x64, 0x5f, 0x6c,
	0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x5f, 0x77, 0x5f, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x72, 0x65, 0x70, 0x5f, 0x69, 0x6e, 0x66, 0x65, 0x72,
	0x72, 0x65, 0x64, 0x5f, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x5f, 0x76, 0x31, 0x22, 0xa7, 0x01, 0x0a,
	0x1b, 0x4d, 0x61, 0x73, 0x6b, 0x65, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x57,
	0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x64, 0x0a, 0x0c,
	0x67, 0x65, 0x74, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x41, 0x2e, 0x72, 0x65, 0x70, 0x5f, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x72, 0x65,
	0x64, 0x5f, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x5f, 0x76, 0x31, 0x2e, 0x4d, 0x61, 0x73, 0x6b, 0x65,
	0x64, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x57, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e,
	0x67, 0x73, 0x47, 0x65, 0x6e, 0x52, 0x0b, 0x67, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e,
	0x67, 0x73, 0x1a, 0x22, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67,
	0x73, 0x47, 0x65, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x03, 0x69, 0x64, 0x73, 0x22, 0xdf, 0x01, 0x0a, 0x1c, 0x4d, 0x61, 0x73, 0x6b, 0x65,
	0x64, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x57, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5b, 0x0a, 0x08, 0x6c, 0x69, 0x73, 0x74, 0x69,
	0x6e, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x3f, 0x2e, 0x72, 0x65, 0x70, 0x5f,
	0x69, 0x6e, 0x66, 0x65, 0x72, 0x72, 0x65, 0x64, 0x5f, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x5f, 0x76,
	0x31, 0x2e, 0x4d, 0x61, 0x73, 0x6b, 0x65, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x73,
	0x57, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x47, 0x65, 0x6e, 0x52, 0x08, 0x6c, 0x69, 0x73, 0x74,
	0x69, 0x6e, 0x67, 0x73, 0x1a, 0x62, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x73,
	0x47, 0x65, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x70,
	0x68, 0x6f, 0x74, 0x6f, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x70, 0x68, 0x6f, 0x74, 0x6f, 0x55, 0x72, 0x6c, 0x32, 0xa5, 0x01, 0x0a, 0x1b, 0x4d, 0x61, 0x73,
	0x6b, 0x65, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x57, 0x4d, 0x65, 0x64, 0x69,
	0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x85, 0x01, 0x0a, 0x1a, 0x49, 0x6e, 0x76,
	0x6f, 0x6b, 0x65, 0x4d, 0x61, 0x73, 0x6b, 0x65, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67,
	0x73, 0x57, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x12, 0x32, 0x2e, 0x72, 0x65, 0x70, 0x5f, 0x69, 0x6e,
	0x66, 0x65, 0x72, 0x72, 0x65, 0x64, 0x5f, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x5f, 0x76, 0x31, 0x2e,
	0x4d, 0x61, 0x73, 0x6b, 0x65, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x57, 0x4d,
	0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x33, 0x2e, 0x72, 0x65,
	0x70, 0x5f, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x72, 0x65, 0x64, 0x5f, 0x69, 0x6e, 0x70, 0x75, 0x74,
	0x5f, 0x76, 0x31, 0x2e, 0x4d, 0x61, 0x73, 0x6b, 0x65, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e,
	0x67, 0x73, 0x57, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x44, 0x5a, 0x42, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63,
	0x61, 0x72, 0x6f, 0x75, 0x73, 0x65, 0x6c, 0x6c, 0x2f, 0x61, 0x67, 0x67, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2f, 0x67, 0x6f, 0x4f, 0x75, 0x74,
	0x2f, 0x72, 0x65, 0x70, 0x5f, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x72, 0x65, 0x64, 0x5f, 0x69, 0x6e,
	0x70, 0x75, 0x74, 0x5f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rep_inferred_input_v1_masked_listings_w_media_proto_rawDescOnce sync.Once
	file_rep_inferred_input_v1_masked_listings_w_media_proto_rawDescData = file_rep_inferred_input_v1_masked_listings_w_media_proto_rawDesc
)

func file_rep_inferred_input_v1_masked_listings_w_media_proto_rawDescGZIP() []byte {
	file_rep_inferred_input_v1_masked_listings_w_media_proto_rawDescOnce.Do(func() {
		file_rep_inferred_input_v1_masked_listings_w_media_proto_rawDescData = protoimpl.X.CompressGZIP(file_rep_inferred_input_v1_masked_listings_w_media_proto_rawDescData)
	})
	return file_rep_inferred_input_v1_masked_listings_w_media_proto_rawDescData
}

var file_rep_inferred_input_v1_masked_listings_w_media_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rep_inferred_input_v1_masked_listings_w_media_proto_goTypes = []interface{}{
	(*MaskedListingsWMediaRequest)(nil),                // 0: rep_inferred_input_v1.MaskedListingsWMediaRequest
	(*MaskedListingsWMediaResponse)(nil),               // 1: rep_inferred_input_v1.MaskedListingsWMediaResponse
	(*MaskedListingsWMediaRequest_GetListingsGen)(nil), // 2: rep_inferred_input_v1.MaskedListingsWMediaRequest.GetListingsGen
	(*MaskedListingsWMediaResponse_ListingsGen)(nil),   // 3: rep_inferred_input_v1.MaskedListingsWMediaResponse.ListingsGen
}
var file_rep_inferred_input_v1_masked_listings_w_media_proto_depIdxs = []int32{
	2, // 0: rep_inferred_input_v1.MaskedListingsWMediaRequest.get_listings:type_name -> rep_inferred_input_v1.MaskedListingsWMediaRequest.GetListingsGen
	3, // 1: rep_inferred_input_v1.MaskedListingsWMediaResponse.listings:type_name -> rep_inferred_input_v1.MaskedListingsWMediaResponse.ListingsGen
	0, // 2: rep_inferred_input_v1.MaskedListingsWMediaService.InvokeMaskedListingsWMedia:input_type -> rep_inferred_input_v1.MaskedListingsWMediaRequest
	1, // 3: rep_inferred_input_v1.MaskedListingsWMediaService.InvokeMaskedListingsWMedia:output_type -> rep_inferred_input_v1.MaskedListingsWMediaResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rep_inferred_input_v1_masked_listings_w_media_proto_init() }
func file_rep_inferred_input_v1_masked_listings_w_media_proto_init() {
	if File_rep_inferred_input_v1_masked_listings_w_media_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rep_inferred_input_v1_masked_listings_w_media_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MaskedListingsWMediaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rep_inferred_input_v1_masked_listings_w_media_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MaskedListingsWMediaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rep_inferred_input_v1_masked_listings_w_media_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MaskedListingsWMediaRequest_GetListingsGen); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rep_inferred_input_v1_masked_listings_w_media_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MaskedListingsWMediaResponse_ListingsGen); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rep_inferred_input_v1_masked_listings_w_media_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rep_inferred_input_v1_masked_listings_w_media_proto_goTypes,
		DependencyIndexes: file_rep_inferred_input_v1_masked_listings_w_media_proto_depIdxs,
		MessageInfos:      file_rep_inferred_input_v1_masked_listings_w_media_proto_msgTypes,
	}.Build()
	File_rep_inferred_input_v1_masked_listings_w_media_proto = out.File
	file_rep_inferred_input_v1_masked_listings_w_media_proto_rawDesc = nil
	file_rep_inferred_input_v1_masked_listings_w_media_proto_goTypes = nil
	file_rep_inferred_input_v1_masked_listings_w_media_proto_depIdxs = nil
}
