// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: alias_union_mask_v1/masked_listing_w_wallet.proto

package alias_union_mask_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MaskedListingWWalletRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GetListingRequest    *MaskedListingWWalletRequest_GetListingRequestGen    `protobuf:"bytes,1,opt,name=get_listing_request,json=getListingRequest,proto3" json:"get_listing_request,omitempty"`
	GetUserWalletRequest *MaskedListingWWalletRequest_GetUserWalletRequestGen `protobuf:"bytes,2,opt,name=get_user_wallet_request,json=getUserWalletRequest,proto3" json:"get_user_wallet_request,omitempty"`
}

func (x *MaskedListingWWalletRequest) Reset() {
	*x = MaskedListingWWalletRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alias_union_mask_v1_masked_listing_w_wallet_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MaskedListingWWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaskedListingWWalletRequest) ProtoMessage() {}

func (x *MaskedListingWWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alias_union_mask_v1_masked_listing_w_wallet_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaskedListingWWalletRequest.ProtoReflect.Descriptor instead.
func (*MaskedListingWWalletRequest) Descriptor() ([]byte, []int) {
	return file_alias_union_mask_v1_masked_listing_w_wallet_proto_rawDescGZIP(), []int{0}
}

func (x *MaskedListingWWalletRequest) GetGetListingRequest() *MaskedListingWWalletRequest_GetListingRequestGen {
	if x != nil {
		return x.GetListingRequest
	}
	return nil
}

func (x *MaskedListingWWalletRequest) GetGetUserWalletRequest() *MaskedListingWWalletRequest_GetUserWalletRequestGen {
	if x != nil {
		return x.GetUserWalletRequest
	}
	return nil
}

type MaskedListingWWalletResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Listing *MaskedListingWWalletResponse_ListingGen `protobuf:"bytes,1,opt,name=listing,proto3" json:"listing,omitempty"`
	Wallet  *MaskedListingWWalletResponse_WalletGen  `protobuf:"bytes,2,opt,name=wallet,proto3" json:"wallet,omitempty"`
}

func (x *MaskedListingWWalletResponse) Reset() {
	*x = MaskedListingWWalletResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alias_union_mask_v1_masked_listing_w_wallet_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MaskedListingWWalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaskedListingWWalletResponse) ProtoMessage() {}

func (x *MaskedListingWWalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alias_union_mask_v1_masked_listing_w_wallet_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaskedListingWWalletResponse.ProtoReflect.Descriptor instead.
func (*MaskedListingWWalletResponse) Descriptor() ([]byte, []int) {
	return file_alias_union_mask_v1_masked_listing_w_wallet_proto_rawDescGZIP(), []int{1}
}

func (x *MaskedListingWWalletResponse) GetListing() *MaskedListingWWalletResponse_ListingGen {
	if x != nil {
		return x.Listing
	}
	return nil
}

func (x *MaskedListingWWalletResponse) GetWallet() *MaskedListingWWalletResponse_WalletGen {
	if x != nil {
		return x.Wallet
	}
	return nil
}

type MaskedListingWWalletRequest_GetListingRequestGen struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ListingId string `protobuf:"bytes,1,opt,name=listing_id,json=listingId,proto3" json:"listing_id,omitempty"`
}

func (x *MaskedListingWWalletRequest_GetListingRequestGen) Reset() {
	*x = MaskedListingWWalletRequest_GetListingRequestGen{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alias_union_mask_v1_masked_listing_w_wallet_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MaskedListingWWalletRequest_GetListingRequestGen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaskedListingWWalletRequest_GetListingRequestGen) ProtoMessage() {}

func (x *MaskedListingWWalletRequest_GetListingRequestGen) ProtoReflect() protoreflect.Message {
	mi := &file_alias_union_mask_v1_masked_listing_w_wallet_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaskedListingWWalletRequest_GetListingRequestGen.ProtoReflect.Descriptor instead.
func (*MaskedListingWWalletRequest_GetListingRequestGen) Descriptor() ([]byte, []int) {
	return file_alias_union_mask_v1_masked_listing_w_wallet_proto_rawDescGZIP(), []int{0, 0}
}

func (x *MaskedListingWWalletRequest_GetListingRequestGen) GetListingId() string {
	if x != nil {
		return x.ListingId
	}
	return ""
}

type MaskedListingWWalletRequest_GetUserWalletRequestGen struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *MaskedListingWWalletRequest_GetUserWalletRequestGen) Reset() {
	*x = MaskedListingWWalletRequest_GetUserWalletRequestGen{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alias_union_mask_v1_masked_listing_w_wallet_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MaskedListingWWalletRequest_GetUserWalletRequestGen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaskedListingWWalletRequest_GetUserWalletRequestGen) ProtoMessage() {}

func (x *MaskedListingWWalletRequest_GetUserWalletRequestGen) ProtoReflect() protoreflect.Message {
	mi := &file_alias_union_mask_v1_masked_listing_w_wallet_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaskedListingWWalletRequest_GetUserWalletRequestGen.ProtoReflect.Descriptor instead.
func (*MaskedListingWWalletRequest_GetUserWalletRequestGen) Descriptor() ([]byte, []int) {
	return file_alias_union_mask_v1_masked_listing_w_wallet_proto_rawDescGZIP(), []int{0, 1}
}

func (x *MaskedListingWWalletRequest_GetUserWalletRequestGen) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type MaskedListingWWalletResponse_ListingGen struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title       string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *MaskedListingWWalletResponse_ListingGen) Reset() {
	*x = MaskedListingWWalletResponse_ListingGen{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alias_union_mask_v1_masked_listing_w_wallet_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MaskedListingWWalletResponse_ListingGen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaskedListingWWalletResponse_ListingGen) ProtoMessage() {}

func (x *MaskedListingWWalletResponse_ListingGen) ProtoReflect() protoreflect.Message {
	mi := &file_alias_union_mask_v1_masked_listing_w_wallet_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaskedListingWWalletResponse_ListingGen.ProtoReflect.Descriptor instead.
func (*MaskedListingWWalletResponse_ListingGen) Descriptor() ([]byte, []int) {
	return file_alias_union_mask_v1_masked_listing_w_wallet_proto_rawDescGZIP(), []int{1, 0}
}

func (x *MaskedListingWWalletResponse_ListingGen) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MaskedListingWWalletResponse_ListingGen) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type MaskedListingWWalletResponse_WalletGen struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Balance int64 `protobuf:"varint,1,opt,name=balance,proto3" json:"balance,omitempty"`
}

func (x *MaskedListingWWalletResponse_WalletGen) Reset() {
	*x = MaskedListingWWalletResponse_WalletGen{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alias_union_mask_v1_masked_listing_w_wallet_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MaskedListingWWalletResponse_WalletGen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaskedListingWWalletResponse_WalletGen) ProtoMessage() {}

func (x *MaskedListingWWalletResponse_WalletGen) ProtoReflect() protoreflect.Message {
	mi := &file_alias_union_mask_v1_masked_listing_w_wallet_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaskedListingWWalletResponse_WalletGen.ProtoReflect.Descriptor instead.
func (*MaskedListingWWalletResponse_WalletGen) Descriptor() ([]byte, []int) {
	return file_alias_union_mask_v1_masked_listing_w_wallet_proto_rawDescGZIP(), []int{1, 1}
}

func (x *MaskedListingWWalletResponse_WalletGen) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

var File_alias_union_mask_v1_masked_listing_w_wallet_proto protoreflect.FileDescriptor

var file_alias_union_mask_v1_masked_listing_w_wallet_proto_rawDesc = []byte{
	0x0a, 0x31, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x5f, 0x75, 0x6e, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x61,
	0x73, 0x6b, 0x5f, 0x76, 0x31, 0x2f, 0x6d, 0x61, 0x73, 0x6b, 0x65, 0x64, 0x5f, 0x6c, 0x69, 0x73,
	0x74, 0x69, 0x6e, 0x67, 0x5f, 0x77, 0x5f, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x13, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x5f, 0x75, 0x6e, 0x69, 0x6f, 0x6e,
	0x5f, 0x6d, 0x61, 0x73, 0x6b, 0x5f, 0x76, 0x31, 0x22, 0x80, 0x03, 0x0a, 0x1b, 0x4d, 0x61, 0x73,
	0x6b, 0x65, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x57, 0x57, 0x61, 0x6c, 0x6c, 0x65,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x75, 0x0a, 0x13, 0x67, 0x65, 0x74, 0x5f,
	0x6c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x45, 0x2e, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x5f, 0x75, 0x6e,
	0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x61, 0x73, 0x6b, 0x5f, 0x76, 0x31, 0x2e, 0x4d, 0x61, 0x73, 0x6b,
	0x65, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x57, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x47, 0x65, 0x6e, 0x52, 0x11, 0x67, 0x65,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x7f, 0x0a, 0x17, 0x67, 0x65, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x77, 0x61, 0x6c, 0x6c,
	0x65, 0x74, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x48, 0x2e, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x5f, 0x75, 0x6e, 0x69, 0x6f, 0x6e, 0x5f, 0x6d,
	0x61, 0x73, 0x6b, 0x5f, 0x76, 0x31, 0x2e, 0x4d, 0x61, 0x73, 0x6b, 0x65, 0x64, 0x4c, 0x69, 0x73,
	0x74, 0x69, 0x6e, 0x67, 0x57, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x47, 0x65, 0x6e, 0x52, 0x14, 0x67, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x35, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x47, 0x65, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x69, 0x73, 0x74,
	0x69, 0x6e, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6c, 0x69,
	0x73, 0x74, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x1a, 0x32, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x47,
	0x65, 0x6e, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0xb8, 0x02, 0x0a, 0x1c,
	0x4d, 0x61, 0x73, 0x6b, 0x65, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x57, 0x57, 0x61,
	0x6c, 0x6c, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x56, 0x0a, 0x07,
	0x6c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3c, 0x2e,
	0x61, 0x6c, 0x69, 0x61, 0x73, 0x5f, 0x75, 0x6e, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x61, 0x73, 0x6b,
	0x5f, 0x76, 0x31, 0x2e, 0x4d, 0x61, 0x73, 0x6b, 0x65, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e,
	0x67, 0x57, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x47, 0x65, 0x6e, 0x52, 0x07, 0x6c, 0x69, 0x73,
	0x74, 0x69, 0x6e, 0x67, 0x12, 0x53, 0x0a, 0x06, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x3b, 0x2e, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x5f, 0x75, 0x6e, 0x69,
	0x6f, 0x6e, 0x5f, 0x6d, 0x61, 0x73, 0x6b, 0x5f, 0x76, 0x31, 0x2e, 0x4d, 0x61, 0x73, 0x6b, 0x65,
	0x64, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x57, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x47, 0x65,
	0x6e, 0x52, 0x06, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x1a, 0x44, 0x0a, 0x0a, 0x4c, 0x69, 0x73,
	0x74, 0x69, 0x6e, 0x67, 0x47, 0x65, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x1a,
	0x25, 0x0a, 0x09, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x47, 0x65, 0x6e, 0x12, 0x18, 0x0a, 0x07,
	0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x62,
	0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x32, 0xa1, 0x01, 0x0a, 0x1b, 0x4d, 0x61, 0x73, 0x6b, 0x65,
	0x64, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x57, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x81, 0x01, 0x0a, 0x1a, 0x49, 0x6e, 0x76, 0x6f, 0x6b,
	0x65, 0x4d, 0x61, 0x73, 0x6b, 0x65, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x57, 0x57,
	0x61, 0x6c, 0x6c, 0x65, 0x74, 0x12, 0x30, 0x2e, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x5f, 0x75, 0x6e,
	0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x61, 0x73, 0x6b, 0x5f, 0x76, 0x31, 0x2e, 0x4d, 0x61, 0x73, 0x6b,
	0x65, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x57, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x31, 0x2e, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x5f,
	0x75, 0x6e, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x61, 0x73, 0x6b, 0x5f, 0x76, 0x31, 0x2e, 0x4d, 0x61,
	0x73, 0x6b, 0x65, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x57, 0x57, 0x61, 0x6c, 0x6c,
	0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x42, 0x5a, 0x40, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x61, 0x72, 0x6f, 0x75, 0x73, 0x65,
	0x6c, 0x6c, 0x2f, 0x61, 0x67, 0x67, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x78, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x73, 0x2f, 0x67, 0x6f, 0x4f, 0x75, 0x74, 0x2f, 0x61, 0x6c, 0x69, 0x61, 0x73,
	0x5f, 0x75, 0x6e, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x61, 0x73, 0x6b, 0x5f, 0x76, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_alias_union_mask_v1_masked_listing_w_wallet_proto_rawDescOnce sync.Once
	file_alias_union_mask_v1_masked_listing_w_wallet_proto_rawDescData = file_alias_union_mask_v1_masked_listing_w_wallet_proto_rawDesc
)

func file_alias_union_mask_v1_masked_listing_w_wallet_proto_rawDescGZIP() []byte {
	file_alias_union_mask_v1_masked_listing_w_wallet_proto_rawDescOnce.Do(func() {
		file_alias_union_mask_v1_masked_listing_w_wallet_proto_rawDescData = protoimpl.X.CompressGZIP(file_alias_union_mask_v1_masked_listing_w_wallet_proto_rawDescData)
	})
	return file_alias_union_mask_v1_masked_listing_w_wallet_proto_rawDescData
}

var file_alias_union_mask_v1_masked_listing_w_wallet_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_alias_union_mask_v1_masked_listing_w_wallet_proto_goTypes = []interface{}{
	(*MaskedListingWWalletRequest)(nil),                         // 0: alias_union_mask_v1.MaskedListingWWalletRequest
	(*MaskedListingWWalletResponse)(nil),                        // 1: alias_union_mask_v1.MaskedListingWWalletResponse
	(*MaskedListingWWalletRequest_GetListingRequestGen)(nil),    // 2: alias_union_mask_v1.MaskedListingWWalletRequest.GetListingRequestGen
	(*MaskedListingWWalletRequest_GetUserWalletRequestGen)(nil), // 3: alias_union_mask_v1.MaskedListingWWalletRequest.GetUserWalletRequestGen
	(*MaskedListingWWalletResponse_ListingGen)(nil),             // 4: alias_union_mask_v1.MaskedListingWWalletResponse.ListingGen
	(*MaskedListingWWalletResponse_WalletGen)(nil),              // 5: alias_union_mask_v1.MaskedListingWWalletResponse.WalletGen
}
var file_alias_union_mask_v1_masked_listing_w_wallet_proto_depIdxs = []int32{
	2, // 0: alias_union_mask_v1.MaskedListingWWalletRequest.get_listing_request:type_name -> alias_union_mask_v1.MaskedListingWWalletRequest.GetListingRequestGen
	3, // 1: alias_union_mask_v1.MaskedListingWWalletRequest.get_user_wallet_request:type_name -> alias_union_mask_v1.MaskedListingWWalletRequest.GetUserWalletRequestGen
	4, // 2: alias_union_mask_v1.MaskedListingWWalletResponse.listing:type_name -> alias_union_mask_v1.MaskedListingWWalletResponse.ListingGen
	5, // 3: alias_union_mask_v1.MaskedListingWWalletResponse.wallet:type_name -> alias_union_mask_v1.MaskedListingWWalletResponse.WalletGen
	0, // 4: alias_union_mask_v1.MaskedListingWWalletService.InvokeMaskedListingWWallet:input_type -> alias_union_mask_v1.MaskedListingWWalletRequest
	1, // 5: alias_union_mask_v1.MaskedListingWWalletService.InvokeMaskedListingWWallet:output_type -> alias_union_mask_v1.MaskedListingWWalletResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_alias_union_mask_v1_masked_listing_w_wallet_proto_init() }
func file_alias_union_mask_v1_masked_listing_w_wallet_proto_init() {
	if File_alias_union_mask_v1_masked_listing_w_wallet_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_alias_union_mask_v1_masked_listing_w_wallet_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MaskedListingWWalletRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alias_union_mask_v1_masked_listing_w_wallet_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MaskedListingWWalletResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alias_union_mask_v1_masked_listing_w_wallet_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MaskedListingWWalletRequest_GetListingRequestGen); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alias_union_mask_v1_masked_listing_w_wallet_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MaskedListingWWalletRequest_GetUserWalletRequestGen); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alias_union_mask_v1_masked_listing_w_wallet_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MaskedListingWWalletResponse_ListingGen); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alias_union_mask_v1_masked_listing_w_wallet_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MaskedListingWWalletResponse_WalletGen); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_alias_union_mask_v1_masked_listing_w_wallet_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_alias_union_mask_v1_masked_listing_w_wallet_proto_goTypes,
		DependencyIndexes: file_alias_union_mask_v1_masked_listing_w_wallet_proto_depIdxs,
		MessageInfos:      file_alias_union_mask_v1_masked_listing_w_wallet_proto_msgTypes,
	}.Build()
	File_alias_union_mask_v1_masked_listing_w_wallet_proto = out.File
	file_alias_union_mask_v1_masked_listing_w_wallet_proto_rawDesc = nil
	file_alias_union_mask_v1_masked_listing_w_wallet_proto_goTypes = nil
	file_alias_union_mask_v1_masked_listing_w_wallet_proto_depIdxs = nil
}
