// Code generated by protoc-gen-go. DO NOT EDIT.
// source: static_primitives_v1/mock_listing.proto

package static_primitives_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MockListingRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MockListingRequest) Reset()         { *m = MockListingRequest{} }
func (m *MockListingRequest) String() string { return proto.CompactTextString(m) }
func (*MockListingRequest) ProtoMessage()    {}
func (*MockListingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4fc6312e5e276a53, []int{0}
}

func (m *MockListingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MockListingRequest.Unmarshal(m, b)
}
func (m *MockListingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MockListingRequest.Marshal(b, m, deterministic)
}
func (m *MockListingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MockListingRequest.Merge(m, src)
}
func (m *MockListingRequest) XXX_Size() int {
	return xxx_messageInfo_MockListingRequest.Size(m)
}
func (m *MockListingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MockListingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MockListingRequest proto.InternalMessageInfo

type MockListingResponse struct {
	Listing              *MockListingResponse_ListingGen `protobuf:"bytes,1,opt,name=listing,proto3" json:"listing,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *MockListingResponse) Reset()         { *m = MockListingResponse{} }
func (m *MockListingResponse) String() string { return proto.CompactTextString(m) }
func (*MockListingResponse) ProtoMessage()    {}
func (*MockListingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4fc6312e5e276a53, []int{1}
}

func (m *MockListingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MockListingResponse.Unmarshal(m, b)
}
func (m *MockListingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MockListingResponse.Marshal(b, m, deterministic)
}
func (m *MockListingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MockListingResponse.Merge(m, src)
}
func (m *MockListingResponse) XXX_Size() int {
	return xxx_messageInfo_MockListingResponse.Size(m)
}
func (m *MockListingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MockListingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MockListingResponse proto.InternalMessageInfo

func (m *MockListingResponse) GetListing() *MockListingResponse_ListingGen {
	if m != nil {
		return m.Listing
	}
	return nil
}

type MockListingResponse_ListingGen struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MockListingResponse_ListingGen) Reset()         { *m = MockListingResponse_ListingGen{} }
func (m *MockListingResponse_ListingGen) String() string { return proto.CompactTextString(m) }
func (*MockListingResponse_ListingGen) ProtoMessage()    {}
func (*MockListingResponse_ListingGen) Descriptor() ([]byte, []int) {
	return fileDescriptor_4fc6312e5e276a53, []int{1, 0}
}

func (m *MockListingResponse_ListingGen) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MockListingResponse_ListingGen.Unmarshal(m, b)
}
func (m *MockListingResponse_ListingGen) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MockListingResponse_ListingGen.Marshal(b, m, deterministic)
}
func (m *MockListingResponse_ListingGen) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MockListingResponse_ListingGen.Merge(m, src)
}
func (m *MockListingResponse_ListingGen) XXX_Size() int {
	return xxx_messageInfo_MockListingResponse_ListingGen.Size(m)
}
func (m *MockListingResponse_ListingGen) XXX_DiscardUnknown() {
	xxx_messageInfo_MockListingResponse_ListingGen.DiscardUnknown(m)
}

var xxx_messageInfo_MockListingResponse_ListingGen proto.InternalMessageInfo

func (m *MockListingResponse_ListingGen) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *MockListingResponse_ListingGen) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*MockListingRequest)(nil), "static_primitives_v1.MockListingRequest")
	proto.RegisterType((*MockListingResponse)(nil), "static_primitives_v1.MockListingResponse")
	proto.RegisterType((*MockListingResponse_ListingGen)(nil), "static_primitives_v1.MockListingResponse.ListingGen")
}

func init() {
	proto.RegisterFile("static_primitives_v1/mock_listing.proto", fileDescriptor_4fc6312e5e276a53)
}

var fileDescriptor_4fc6312e5e276a53 = []byte{
	// 255 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0xcd, 0x4a, 0x03, 0x31,
	0x14, 0x85, 0x19, 0x41, 0xc5, 0x74, 0x65, 0x9c, 0x45, 0xe9, 0xaa, 0x74, 0x63, 0xdd, 0x4c, 0xb0,
	0xfa, 0x02, 0xfe, 0x80, 0x08, 0xfe, 0xc0, 0xb8, 0x73, 0x33, 0x4c, 0xe3, 0x25, 0xbd, 0x4c, 0x26,
	0x37, 0x26, 0x77, 0x06, 0x57, 0xbe, 0x90, 0x2f, 0x29, 0xa4, 0x15, 0x5b, 0x98, 0x45, 0x97, 0xf7,
	0x9c, 0x93, 0x8f, 0x9c, 0x23, 0xce, 0x23, 0xd7, 0x8c, 0xba, 0xf2, 0x01, 0x5b, 0x64, 0xec, 0x21,
	0x56, 0xfd, 0xa5, 0x6a, 0x49, 0x37, 0x95, 0xc5, 0xc8, 0xe8, 0x4c, 0xe1, 0x03, 0x31, 0xc9, 0x7c,
	0x28, 0x38, 0xcb, 0x85, 0x7c, 0x26, 0xdd, 0x3c, 0xad, 0xa3, 0x25, 0x7c, 0x76, 0x10, 0x79, 0xf6,
	0x93, 0x89, 0xb3, 0x1d, 0x39, 0x7a, 0x72, 0x11, 0xe4, 0x8b, 0x38, 0xde, 0x40, 0xc7, 0xd9, 0x34,
	0x9b, 0x8f, 0x16, 0xd7, 0xc5, 0x10, 0xb5, 0x18, 0x78, 0x5b, 0x6c, 0xee, 0x07, 0x70, 0xe5, 0x1f,
	0x64, 0x72, 0x2f, 0xc4, 0xbf, 0x2c, 0x73, 0x71, 0xc8, 0xc8, 0x16, 0x12, 0xfb, 0xa4, 0x5c, 0x1f,
	0x72, 0x2a, 0x46, 0x1f, 0x10, 0x75, 0x40, 0xcf, 0x48, 0x6e, 0x7c, 0x90, 0xbc, 0x6d, 0x69, 0xf1,
	0xbd, 0xd3, 0xe1, 0x0d, 0x42, 0x8f, 0x1a, 0xe4, 0x4a, 0x9c, 0x3e, 0xba, 0x9e, 0x1a, 0xd8, 0xf2,
	0xe4, 0x7c, 0x8f, 0xff, 0xa6, 0x09, 0x26, 0x17, 0x7b, 0x37, 0xbb, 0xbd, 0x7b, 0xbf, 0x31, 0xc8,
	0xab, 0x6e, 0x59, 0x68, 0x6a, 0x95, 0xae, 0x03, 0x75, 0x11, 0xac, 0x55, 0xb5, 0x31, 0x69, 0x7a,
	0x05, 0x5f, 0x75, 0xeb, 0x2d, 0x44, 0x65, 0xe8, 0xb5, 0x63, 0x35, 0x04, 0x5e, 0x1e, 0xa5, 0xe8,
	0xd5, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb8, 0xd6, 0x0d, 0xad, 0xd0, 0x01, 0x00, 0x00,
}
