// Code generated by protoc-gen-go. DO NOT EDIT.
// source: listing_comments/comments.proto

package listing_comments

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetListingCommentsRequest struct {
	ListingId            string   `protobuf:"bytes,1,opt,name=listing_id,json=listingId,proto3" json:"listing_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetListingCommentsRequest) Reset()         { *m = GetListingCommentsRequest{} }
func (m *GetListingCommentsRequest) String() string { return proto.CompactTextString(m) }
func (*GetListingCommentsRequest) ProtoMessage()    {}
func (*GetListingCommentsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb3598f166b3265e, []int{0}
}

func (m *GetListingCommentsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListingCommentsRequest.Unmarshal(m, b)
}
func (m *GetListingCommentsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListingCommentsRequest.Marshal(b, m, deterministic)
}
func (m *GetListingCommentsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListingCommentsRequest.Merge(m, src)
}
func (m *GetListingCommentsRequest) XXX_Size() int {
	return xxx_messageInfo_GetListingCommentsRequest.Size(m)
}
func (m *GetListingCommentsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListingCommentsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetListingCommentsRequest proto.InternalMessageInfo

func (m *GetListingCommentsRequest) GetListingId() string {
	if m != nil {
		return m.ListingId
	}
	return ""
}

type ListingComment struct {
	Comments             []*ListingComment_Comment `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ListingComment) Reset()         { *m = ListingComment{} }
func (m *ListingComment) String() string { return proto.CompactTextString(m) }
func (*ListingComment) ProtoMessage()    {}
func (*ListingComment) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb3598f166b3265e, []int{1}
}

func (m *ListingComment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListingComment.Unmarshal(m, b)
}
func (m *ListingComment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListingComment.Marshal(b, m, deterministic)
}
func (m *ListingComment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListingComment.Merge(m, src)
}
func (m *ListingComment) XXX_Size() int {
	return xxx_messageInfo_ListingComment.Size(m)
}
func (m *ListingComment) XXX_DiscardUnknown() {
	xxx_messageInfo_ListingComment.DiscardUnknown(m)
}

var xxx_messageInfo_ListingComment proto.InternalMessageInfo

func (m *ListingComment) GetComments() []*ListingComment_Comment {
	if m != nil {
		return m.Comments
	}
	return nil
}

type ListingComment_Comment struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Body                 string   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListingComment_Comment) Reset()         { *m = ListingComment_Comment{} }
func (m *ListingComment_Comment) String() string { return proto.CompactTextString(m) }
func (*ListingComment_Comment) ProtoMessage()    {}
func (*ListingComment_Comment) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb3598f166b3265e, []int{1, 0}
}

func (m *ListingComment_Comment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListingComment_Comment.Unmarshal(m, b)
}
func (m *ListingComment_Comment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListingComment_Comment.Marshal(b, m, deterministic)
}
func (m *ListingComment_Comment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListingComment_Comment.Merge(m, src)
}
func (m *ListingComment_Comment) XXX_Size() int {
	return xxx_messageInfo_ListingComment_Comment.Size(m)
}
func (m *ListingComment_Comment) XXX_DiscardUnknown() {
	xxx_messageInfo_ListingComment_Comment.DiscardUnknown(m)
}

var xxx_messageInfo_ListingComment_Comment proto.InternalMessageInfo

func (m *ListingComment_Comment) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ListingComment_Comment) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type GetListingCommentsResponse struct {
	ListingComment       *ListingComment `protobuf:"bytes,1,opt,name=listing_comment,json=listingComment,proto3" json:"listing_comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetListingCommentsResponse) Reset()         { *m = GetListingCommentsResponse{} }
func (m *GetListingCommentsResponse) String() string { return proto.CompactTextString(m) }
func (*GetListingCommentsResponse) ProtoMessage()    {}
func (*GetListingCommentsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb3598f166b3265e, []int{2}
}

func (m *GetListingCommentsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListingCommentsResponse.Unmarshal(m, b)
}
func (m *GetListingCommentsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListingCommentsResponse.Marshal(b, m, deterministic)
}
func (m *GetListingCommentsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListingCommentsResponse.Merge(m, src)
}
func (m *GetListingCommentsResponse) XXX_Size() int {
	return xxx_messageInfo_GetListingCommentsResponse.Size(m)
}
func (m *GetListingCommentsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListingCommentsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetListingCommentsResponse proto.InternalMessageInfo

func (m *GetListingCommentsResponse) GetListingComment() *ListingComment {
	if m != nil {
		return m.ListingComment
	}
	return nil
}

type BulkGetListingCommentsRequest struct {
	ListingId            []string `protobuf:"bytes,1,rep,name=listing_id,json=listingId,proto3" json:"listing_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BulkGetListingCommentsRequest) Reset()         { *m = BulkGetListingCommentsRequest{} }
func (m *BulkGetListingCommentsRequest) String() string { return proto.CompactTextString(m) }
func (*BulkGetListingCommentsRequest) ProtoMessage()    {}
func (*BulkGetListingCommentsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb3598f166b3265e, []int{3}
}

func (m *BulkGetListingCommentsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BulkGetListingCommentsRequest.Unmarshal(m, b)
}
func (m *BulkGetListingCommentsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BulkGetListingCommentsRequest.Marshal(b, m, deterministic)
}
func (m *BulkGetListingCommentsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BulkGetListingCommentsRequest.Merge(m, src)
}
func (m *BulkGetListingCommentsRequest) XXX_Size() int {
	return xxx_messageInfo_BulkGetListingCommentsRequest.Size(m)
}
func (m *BulkGetListingCommentsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BulkGetListingCommentsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BulkGetListingCommentsRequest proto.InternalMessageInfo

func (m *BulkGetListingCommentsRequest) GetListingId() []string {
	if m != nil {
		return m.ListingId
	}
	return nil
}

type BulkGetListingCommentsResponse struct {
	ListingComments      []*ListingComment `protobuf:"bytes,1,rep,name=listing_comments,json=listingComments,proto3" json:"listing_comments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *BulkGetListingCommentsResponse) Reset()         { *m = BulkGetListingCommentsResponse{} }
func (m *BulkGetListingCommentsResponse) String() string { return proto.CompactTextString(m) }
func (*BulkGetListingCommentsResponse) ProtoMessage()    {}
func (*BulkGetListingCommentsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb3598f166b3265e, []int{4}
}

func (m *BulkGetListingCommentsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BulkGetListingCommentsResponse.Unmarshal(m, b)
}
func (m *BulkGetListingCommentsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BulkGetListingCommentsResponse.Marshal(b, m, deterministic)
}
func (m *BulkGetListingCommentsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BulkGetListingCommentsResponse.Merge(m, src)
}
func (m *BulkGetListingCommentsResponse) XXX_Size() int {
	return xxx_messageInfo_BulkGetListingCommentsResponse.Size(m)
}
func (m *BulkGetListingCommentsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BulkGetListingCommentsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BulkGetListingCommentsResponse proto.InternalMessageInfo

func (m *BulkGetListingCommentsResponse) GetListingComments() []*ListingComment {
	if m != nil {
		return m.ListingComments
	}
	return nil
}

func init() {
	proto.RegisterType((*GetListingCommentsRequest)(nil), "listing_comments.GetListingCommentsRequest")
	proto.RegisterType((*ListingComment)(nil), "listing_comments.ListingComment")
	proto.RegisterType((*ListingComment_Comment)(nil), "listing_comments.ListingComment.Comment")
	proto.RegisterType((*GetListingCommentsResponse)(nil), "listing_comments.GetListingCommentsResponse")
	proto.RegisterType((*BulkGetListingCommentsRequest)(nil), "listing_comments.BulkGetListingCommentsRequest")
	proto.RegisterType((*BulkGetListingCommentsResponse)(nil), "listing_comments.BulkGetListingCommentsResponse")
}

func init() { proto.RegisterFile("listing_comments/comments.proto", fileDescriptor_eb3598f166b3265e) }

var fileDescriptor_eb3598f166b3265e = []byte{
	// 322 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xcd, 0x4b, 0xf3, 0x30,
	0x18, 0x7f, 0xbb, 0xbd, 0x7e, 0xec, 0x19, 0xac, 0x12, 0x44, 0x6a, 0x61, 0x5a, 0x7a, 0x2a, 0x28,
	0x8d, 0x74, 0x37, 0x41, 0x85, 0x29, 0xc8, 0x50, 0x10, 0x7a, 0xf4, 0x22, 0xfd, 0x08, 0xb1, 0x98,
	0x36, 0xdd, 0x92, 0x82, 0x1e, 0x3c, 0x79, 0xf4, 0x9f, 0x16, 0xda, 0x54, 0x68, 0xbb, 0xb9, 0x9e,
	0x9a, 0x3c, 0x3c, 0xbf, 0xcf, 0x12, 0x38, 0x65, 0x89, 0x90, 0x49, 0x46, 0x5f, 0x22, 0x9e, 0xa6,
	0x24, 0x93, 0x02, 0xd7, 0x07, 0x37, 0x5f, 0x71, 0xc9, 0xd1, 0x41, 0x7b, 0xc1, 0xbe, 0x84, 0xe3,
	0x7b, 0x22, 0x1f, 0xab, 0xf1, 0xad, 0x9a, 0xfa, 0x64, 0x59, 0x10, 0x21, 0xd1, 0x14, 0xa0, 0x06,
	0x24, 0xb1, 0xa1, 0x59, 0x9a, 0x33, 0xf2, 0x47, 0x6a, 0xb2, 0x88, 0xed, 0x6f, 0x0d, 0x26, 0x4d,
	0x24, 0xba, 0x83, 0xfd, 0x9a, 0xda, 0xd0, 0xac, 0xa1, 0x33, 0xf6, 0x1c, 0xb7, 0xad, 0xe9, 0x36,
	0x31, 0xae, 0xfa, 0xfa, 0xbf, 0x48, 0x73, 0x06, 0x7b, 0x35, 0xe1, 0x21, 0xec, 0xc8, 0x44, 0x32,
	0xa2, 0xd4, 0xab, 0x0b, 0x42, 0xf0, 0x3f, 0xe4, 0xf1, 0x87, 0x31, 0x28, 0x87, 0xe5, 0xd9, 0xa6,
	0x60, 0xae, 0x4b, 0x22, 0x72, 0x9e, 0x09, 0x82, 0x16, 0xa0, 0xb7, 0x7c, 0x94, 0x8c, 0x63, 0xcf,
	0xda, 0xe6, 0xcf, 0x9f, 0xb0, 0xc6, 0xdd, 0xbe, 0x86, 0xe9, 0xbc, 0x60, 0x6f, 0xfd, 0x6b, 0x1b,
	0x36, 0x6b, 0x4b, 0xe1, 0x64, 0x13, 0x5e, 0x99, 0x7d, 0x80, 0xce, 0x8f, 0x52, 0x6d, 0x6e, 0x77,
	0xab, 0x37, 0xdd, 0x0a, 0xef, 0x6b, 0x00, 0x7a, 0x4b, 0x08, 0x2d, 0x01, 0x75, 0xe5, 0xd1, 0x59,
	0x97, 0x7c, 0x63, 0x48, 0xf3, 0xbc, 0xdf, 0x72, 0x95, 0xc8, 0xfe, 0x87, 0x3e, 0xe1, 0x68, 0x7d,
	0x6a, 0x84, 0xbb, 0x4c, 0x7f, 0xf6, 0x6b, 0x5e, 0xf4, 0x07, 0xd4, 0xf2, 0xf3, 0x9b, 0xe7, 0x2b,
	0x9a, 0xc8, 0xd7, 0x22, 0x74, 0x23, 0x9e, 0xe2, 0x28, 0x58, 0xf1, 0x42, 0x10, 0xc6, 0x70, 0x40,
	0x69, 0xf9, 0x34, 0x30, 0x79, 0x0f, 0xd2, 0x9c, 0x11, 0x81, 0x29, 0x7f, 0x2a, 0x24, 0x6e, 0x2b,
	0x84, 0xbb, 0xe5, 0xda, 0xec, 0x27, 0x00, 0x00, 0xff, 0xff, 0xde, 0x44, 0x95, 0x77, 0x64, 0x03,
	0x00, 0x00,
}
