// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: simple_mask_v1/masked_listing.proto

package simple_mask_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MaskedListingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GetListingRequest *MaskedListingRequest_GetListingRequestGen `protobuf:"bytes,1,opt,name=get_listing_request,json=getListingRequest,proto3" json:"get_listing_request,omitempty"`
}

func (x *MaskedListingRequest) Reset() {
	*x = MaskedListingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_simple_mask_v1_masked_listing_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MaskedListingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaskedListingRequest) ProtoMessage() {}

func (x *MaskedListingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_simple_mask_v1_masked_listing_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaskedListingRequest.ProtoReflect.Descriptor instead.
func (*MaskedListingRequest) Descriptor() ([]byte, []int) {
	return file_simple_mask_v1_masked_listing_proto_rawDescGZIP(), []int{0}
}

func (x *MaskedListingRequest) GetGetListingRequest() *MaskedListingRequest_GetListingRequestGen {
	if x != nil {
		return x.GetListingRequest
	}
	return nil
}

type MaskedListingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Listing *MaskedListingResponse_ListingGen `protobuf:"bytes,1,opt,name=listing,proto3" json:"listing,omitempty"`
}

func (x *MaskedListingResponse) Reset() {
	*x = MaskedListingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_simple_mask_v1_masked_listing_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MaskedListingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaskedListingResponse) ProtoMessage() {}

func (x *MaskedListingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_simple_mask_v1_masked_listing_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaskedListingResponse.ProtoReflect.Descriptor instead.
func (*MaskedListingResponse) Descriptor() ([]byte, []int) {
	return file_simple_mask_v1_masked_listing_proto_rawDescGZIP(), []int{1}
}

func (x *MaskedListingResponse) GetListing() *MaskedListingResponse_ListingGen {
	if x != nil {
		return x.Listing
	}
	return nil
}

type MaskedListingRequest_GetListingRequestGen struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ListingId string `protobuf:"bytes,1,opt,name=listing_id,json=listingId,proto3" json:"listing_id,omitempty"`
}

func (x *MaskedListingRequest_GetListingRequestGen) Reset() {
	*x = MaskedListingRequest_GetListingRequestGen{}
	if protoimpl.UnsafeEnabled {
		mi := &file_simple_mask_v1_masked_listing_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MaskedListingRequest_GetListingRequestGen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaskedListingRequest_GetListingRequestGen) ProtoMessage() {}

func (x *MaskedListingRequest_GetListingRequestGen) ProtoReflect() protoreflect.Message {
	mi := &file_simple_mask_v1_masked_listing_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaskedListingRequest_GetListingRequestGen.ProtoReflect.Descriptor instead.
func (*MaskedListingRequest_GetListingRequestGen) Descriptor() ([]byte, []int) {
	return file_simple_mask_v1_masked_listing_proto_rawDescGZIP(), []int{0, 0}
}

func (x *MaskedListingRequest_GetListingRequestGen) GetListingId() string {
	if x != nil {
		return x.ListingId
	}
	return ""
}

type MaskedListingResponse_ListingGen struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GetListingResponse *MaskedListingResponse_ListingGen_GetListingResponseGen `protobuf:"bytes,1,opt,name=GetListingResponse,proto3" json:"GetListingResponse,omitempty"`
}

func (x *MaskedListingResponse_ListingGen) Reset() {
	*x = MaskedListingResponse_ListingGen{}
	if protoimpl.UnsafeEnabled {
		mi := &file_simple_mask_v1_masked_listing_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MaskedListingResponse_ListingGen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaskedListingResponse_ListingGen) ProtoMessage() {}

func (x *MaskedListingResponse_ListingGen) ProtoReflect() protoreflect.Message {
	mi := &file_simple_mask_v1_masked_listing_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaskedListingResponse_ListingGen.ProtoReflect.Descriptor instead.
func (*MaskedListingResponse_ListingGen) Descriptor() ([]byte, []int) {
	return file_simple_mask_v1_masked_listing_proto_rawDescGZIP(), []int{1, 0}
}

func (x *MaskedListingResponse_ListingGen) GetGetListingResponse() *MaskedListingResponse_ListingGen_GetListingResponseGen {
	if x != nil {
		return x.GetListingResponse
	}
	return nil
}

type MaskedListingResponse_ListingGen_GetListingResponseGen struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Listing *MaskedListingResponse_ListingGen_GetListingResponseGen_ListingGen `protobuf:"bytes,1,opt,name=listing,proto3" json:"listing,omitempty"`
}

func (x *MaskedListingResponse_ListingGen_GetListingResponseGen) Reset() {
	*x = MaskedListingResponse_ListingGen_GetListingResponseGen{}
	if protoimpl.UnsafeEnabled {
		mi := &file_simple_mask_v1_masked_listing_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MaskedListingResponse_ListingGen_GetListingResponseGen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaskedListingResponse_ListingGen_GetListingResponseGen) ProtoMessage() {}

func (x *MaskedListingResponse_ListingGen_GetListingResponseGen) ProtoReflect() protoreflect.Message {
	mi := &file_simple_mask_v1_masked_listing_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaskedListingResponse_ListingGen_GetListingResponseGen.ProtoReflect.Descriptor instead.
func (*MaskedListingResponse_ListingGen_GetListingResponseGen) Descriptor() ([]byte, []int) {
	return file_simple_mask_v1_masked_listing_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (x *MaskedListingResponse_ListingGen_GetListingResponseGen) GetListing() *MaskedListingResponse_ListingGen_GetListingResponseGen_ListingGen {
	if x != nil {
		return x.Listing
	}
	return nil
}

type MaskedListingResponse_ListingGen_GetListingResponseGen_ListingGen struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title       string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *MaskedListingResponse_ListingGen_GetListingResponseGen_ListingGen) Reset() {
	*x = MaskedListingResponse_ListingGen_GetListingResponseGen_ListingGen{}
	if protoimpl.UnsafeEnabled {
		mi := &file_simple_mask_v1_masked_listing_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MaskedListingResponse_ListingGen_GetListingResponseGen_ListingGen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaskedListingResponse_ListingGen_GetListingResponseGen_ListingGen) ProtoMessage() {}

func (x *MaskedListingResponse_ListingGen_GetListingResponseGen_ListingGen) ProtoReflect() protoreflect.Message {
	mi := &file_simple_mask_v1_masked_listing_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaskedListingResponse_ListingGen_GetListingResponseGen_ListingGen.ProtoReflect.Descriptor instead.
func (*MaskedListingResponse_ListingGen_GetListingResponseGen_ListingGen) Descriptor() ([]byte, []int) {
	return file_simple_mask_v1_masked_listing_proto_rawDescGZIP(), []int{1, 0, 0, 0}
}

func (x *MaskedListingResponse_ListingGen_GetListingResponseGen_ListingGen) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MaskedListingResponse_ListingGen_GetListingResponseGen_ListingGen) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_simple_mask_v1_masked_listing_proto protoreflect.FileDescriptor

var file_simple_mask_v1_masked_listing_proto_rawDesc = []byte{
	0x0a, 0x23, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x5f, 0x6d, 0x61, 0x73, 0x6b, 0x5f, 0x76, 0x31,
	0x2f, 0x6d, 0x61, 0x73, 0x6b, 0x65, 0x64, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x5f, 0x6d, 0x61,
	0x73, 0x6b, 0x5f, 0x76, 0x31, 0x22, 0xb8, 0x01, 0x0a, 0x14, 0x4d, 0x61, 0x73, 0x6b, 0x65, 0x64,
	0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x69,
	0x0a, 0x13, 0x67, 0x65, 0x74, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x39, 0x2e, 0x73, 0x69,
	0x6d, 0x70, 0x6c, 0x65, 0x5f, 0x6d, 0x61, 0x73, 0x6b, 0x5f, 0x76, 0x31, 0x2e, 0x4d, 0x61, 0x73,
	0x6b, 0x65, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x47, 0x65, 0x6e, 0x52, 0x11, 0x67, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x35, 0x0a, 0x14, 0x47, 0x65, 0x74,
	0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x47, 0x65,
	0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x49, 0x64,
	0x22, 0xb7, 0x03, 0x0a, 0x15, 0x4d, 0x61, 0x73, 0x6b, 0x65, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a, 0x07, 0x6c, 0x69,
	0x73, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x73, 0x69,
	0x6d, 0x70, 0x6c, 0x65, 0x5f, 0x6d, 0x61, 0x73, 0x6b, 0x5f, 0x76, 0x31, 0x2e, 0x4d, 0x61, 0x73,
	0x6b, 0x65, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x47, 0x65, 0x6e, 0x52, 0x07, 0x6c,
	0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x1a, 0xd1, 0x02, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x69,
	0x6e, 0x67, 0x47, 0x65, 0x6e, 0x12, 0x76, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x46, 0x2e, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x5f, 0x6d, 0x61, 0x73, 0x6b, 0x5f,
	0x76, 0x31, 0x2e, 0x4d, 0x61, 0x73, 0x6b, 0x65, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67,
	0x47, 0x65, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x47, 0x65, 0x6e, 0x52, 0x12, 0x47, 0x65, 0x74, 0x4c, 0x69,
	0x73, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x1a, 0xca, 0x01,
	0x0a, 0x15, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x47, 0x65, 0x6e, 0x12, 0x6b, 0x0a, 0x07, 0x6c, 0x69, 0x73, 0x74, 0x69,
	0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x51, 0x2e, 0x73, 0x69, 0x6d, 0x70, 0x6c,
	0x65, 0x5f, 0x6d, 0x61, 0x73, 0x6b, 0x5f, 0x76, 0x31, 0x2e, 0x4d, 0x61, 0x73, 0x6b, 0x65, 0x64,
	0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x47, 0x65, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x69,
	0x73, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x47, 0x65, 0x6e,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x47, 0x65, 0x6e, 0x52, 0x07, 0x6c, 0x69, 0x73,
	0x74, 0x69, 0x6e, 0x67, 0x1a, 0x44, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x47,
	0x65, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0x7a, 0x0a, 0x14, 0x4d, 0x61,
	0x73, 0x6b, 0x65, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x62, 0x0a, 0x13, 0x49, 0x6e, 0x76, 0x6f, 0x6b, 0x65, 0x4d, 0x61, 0x73, 0x6b,
	0x65, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x24, 0x2e, 0x73, 0x69, 0x6d, 0x70,
	0x6c, 0x65, 0x5f, 0x6d, 0x61, 0x73, 0x6b, 0x5f, 0x76, 0x31, 0x2e, 0x4d, 0x61, 0x73, 0x6b, 0x65,
	0x64, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x25, 0x2e, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x5f, 0x6d, 0x61, 0x73, 0x6b, 0x5f, 0x76, 0x31,
	0x2e, 0x4d, 0x61, 0x73, 0x6b, 0x65, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x3d, 0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x61, 0x72, 0x6f, 0x75, 0x73, 0x65, 0x6c, 0x6c, 0x2f, 0x61,
	0x67, 0x67, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73,
	0x2f, 0x67, 0x6f, 0x4f, 0x75, 0x74, 0x2f, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x5f, 0x6d, 0x61,
	0x73, 0x6b, 0x5f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_simple_mask_v1_masked_listing_proto_rawDescOnce sync.Once
	file_simple_mask_v1_masked_listing_proto_rawDescData = file_simple_mask_v1_masked_listing_proto_rawDesc
)

func file_simple_mask_v1_masked_listing_proto_rawDescGZIP() []byte {
	file_simple_mask_v1_masked_listing_proto_rawDescOnce.Do(func() {
		file_simple_mask_v1_masked_listing_proto_rawDescData = protoimpl.X.CompressGZIP(file_simple_mask_v1_masked_listing_proto_rawDescData)
	})
	return file_simple_mask_v1_masked_listing_proto_rawDescData
}

var file_simple_mask_v1_masked_listing_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_simple_mask_v1_masked_listing_proto_goTypes = []interface{}{
	(*MaskedListingRequest)(nil),                                              // 0: simple_mask_v1.MaskedListingRequest
	(*MaskedListingResponse)(nil),                                             // 1: simple_mask_v1.MaskedListingResponse
	(*MaskedListingRequest_GetListingRequestGen)(nil),                         // 2: simple_mask_v1.MaskedListingRequest.GetListingRequestGen
	(*MaskedListingResponse_ListingGen)(nil),                                  // 3: simple_mask_v1.MaskedListingResponse.ListingGen
	(*MaskedListingResponse_ListingGen_GetListingResponseGen)(nil),            // 4: simple_mask_v1.MaskedListingResponse.ListingGen.GetListingResponseGen
	(*MaskedListingResponse_ListingGen_GetListingResponseGen_ListingGen)(nil), // 5: simple_mask_v1.MaskedListingResponse.ListingGen.GetListingResponseGen.ListingGen
}
var file_simple_mask_v1_masked_listing_proto_depIdxs = []int32{
	2, // 0: simple_mask_v1.MaskedListingRequest.get_listing_request:type_name -> simple_mask_v1.MaskedListingRequest.GetListingRequestGen
	3, // 1: simple_mask_v1.MaskedListingResponse.listing:type_name -> simple_mask_v1.MaskedListingResponse.ListingGen
	4, // 2: simple_mask_v1.MaskedListingResponse.ListingGen.GetListingResponse:type_name -> simple_mask_v1.MaskedListingResponse.ListingGen.GetListingResponseGen
	5, // 3: simple_mask_v1.MaskedListingResponse.ListingGen.GetListingResponseGen.listing:type_name -> simple_mask_v1.MaskedListingResponse.ListingGen.GetListingResponseGen.ListingGen
	0, // 4: simple_mask_v1.MaskedListingService.InvokeMaskedListing:input_type -> simple_mask_v1.MaskedListingRequest
	1, // 5: simple_mask_v1.MaskedListingService.InvokeMaskedListing:output_type -> simple_mask_v1.MaskedListingResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_simple_mask_v1_masked_listing_proto_init() }
func file_simple_mask_v1_masked_listing_proto_init() {
	if File_simple_mask_v1_masked_listing_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_simple_mask_v1_masked_listing_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MaskedListingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_simple_mask_v1_masked_listing_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MaskedListingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_simple_mask_v1_masked_listing_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MaskedListingRequest_GetListingRequestGen); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_simple_mask_v1_masked_listing_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MaskedListingResponse_ListingGen); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_simple_mask_v1_masked_listing_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MaskedListingResponse_ListingGen_GetListingResponseGen); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_simple_mask_v1_masked_listing_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MaskedListingResponse_ListingGen_GetListingResponseGen_ListingGen); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_simple_mask_v1_masked_listing_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_simple_mask_v1_masked_listing_proto_goTypes,
		DependencyIndexes: file_simple_mask_v1_masked_listing_proto_depIdxs,
		MessageInfos:      file_simple_mask_v1_masked_listing_proto_msgTypes,
	}.Build()
	File_simple_mask_v1_masked_listing_proto = out.File
	file_simple_mask_v1_masked_listing_proto_rawDesc = nil
	file_simple_mask_v1_masked_listing_proto_goTypes = nil
	file_simple_mask_v1_masked_listing_proto_depIdxs = nil
}
