// Code generated by protoc-gen-go. DO NOT EDIT.
// source: media/media.proto

package media

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Media struct {
	PhotoUrl             string   `protobuf:"bytes,1,opt,name=photo_url,json=photoUrl,proto3" json:"photo_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Media) Reset()         { *m = Media{} }
func (m *Media) String() string { return proto.CompactTextString(m) }
func (*Media) ProtoMessage()    {}
func (*Media) Descriptor() ([]byte, []int) {
	return fileDescriptor_593688da247aaf8b, []int{0}
}

func (m *Media) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Media.Unmarshal(m, b)
}
func (m *Media) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Media.Marshal(b, m, deterministic)
}
func (m *Media) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Media.Merge(m, src)
}
func (m *Media) XXX_Size() int {
	return xxx_messageInfo_Media.Size(m)
}
func (m *Media) XXX_DiscardUnknown() {
	xxx_messageInfo_Media.DiscardUnknown(m)
}

var xxx_messageInfo_Media proto.InternalMessageInfo

func (m *Media) GetPhotoUrl() string {
	if m != nil {
		return m.PhotoUrl
	}
	return ""
}

type GetMediaRequest struct {
	MediaId              string   `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMediaRequest) Reset()         { *m = GetMediaRequest{} }
func (m *GetMediaRequest) String() string { return proto.CompactTextString(m) }
func (*GetMediaRequest) ProtoMessage()    {}
func (*GetMediaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_593688da247aaf8b, []int{1}
}

func (m *GetMediaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMediaRequest.Unmarshal(m, b)
}
func (m *GetMediaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMediaRequest.Marshal(b, m, deterministic)
}
func (m *GetMediaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMediaRequest.Merge(m, src)
}
func (m *GetMediaRequest) XXX_Size() int {
	return xxx_messageInfo_GetMediaRequest.Size(m)
}
func (m *GetMediaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMediaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMediaRequest proto.InternalMessageInfo

func (m *GetMediaRequest) GetMediaId() string {
	if m != nil {
		return m.MediaId
	}
	return ""
}

type GetMediaResponse struct {
	Media                *Media   `protobuf:"bytes,1,opt,name=media,proto3" json:"media,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMediaResponse) Reset()         { *m = GetMediaResponse{} }
func (m *GetMediaResponse) String() string { return proto.CompactTextString(m) }
func (*GetMediaResponse) ProtoMessage()    {}
func (*GetMediaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_593688da247aaf8b, []int{2}
}

func (m *GetMediaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMediaResponse.Unmarshal(m, b)
}
func (m *GetMediaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMediaResponse.Marshal(b, m, deterministic)
}
func (m *GetMediaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMediaResponse.Merge(m, src)
}
func (m *GetMediaResponse) XXX_Size() int {
	return xxx_messageInfo_GetMediaResponse.Size(m)
}
func (m *GetMediaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMediaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMediaResponse proto.InternalMessageInfo

func (m *GetMediaResponse) GetMedia() *Media {
	if m != nil {
		return m.Media
	}
	return nil
}

type BulkGetMediaRequest struct {
	MediaIds             []string `protobuf:"bytes,1,rep,name=media_ids,json=mediaIds,proto3" json:"media_ids,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MediaType            []string `protobuf:"bytes,3,rep,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BulkGetMediaRequest) Reset()         { *m = BulkGetMediaRequest{} }
func (m *BulkGetMediaRequest) String() string { return proto.CompactTextString(m) }
func (*BulkGetMediaRequest) ProtoMessage()    {}
func (*BulkGetMediaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_593688da247aaf8b, []int{3}
}

func (m *BulkGetMediaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BulkGetMediaRequest.Unmarshal(m, b)
}
func (m *BulkGetMediaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BulkGetMediaRequest.Marshal(b, m, deterministic)
}
func (m *BulkGetMediaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BulkGetMediaRequest.Merge(m, src)
}
func (m *BulkGetMediaRequest) XXX_Size() int {
	return xxx_messageInfo_BulkGetMediaRequest.Size(m)
}
func (m *BulkGetMediaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BulkGetMediaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BulkGetMediaRequest proto.InternalMessageInfo

func (m *BulkGetMediaRequest) GetMediaIds() []string {
	if m != nil {
		return m.MediaIds
	}
	return nil
}

func (m *BulkGetMediaRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *BulkGetMediaRequest) GetMediaType() []string {
	if m != nil {
		return m.MediaType
	}
	return nil
}

type BulkGetMediaResponse struct {
	Medias               []*Media `protobuf:"bytes,1,rep,name=medias,proto3" json:"medias,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BulkGetMediaResponse) Reset()         { *m = BulkGetMediaResponse{} }
func (m *BulkGetMediaResponse) String() string { return proto.CompactTextString(m) }
func (*BulkGetMediaResponse) ProtoMessage()    {}
func (*BulkGetMediaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_593688da247aaf8b, []int{4}
}

func (m *BulkGetMediaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BulkGetMediaResponse.Unmarshal(m, b)
}
func (m *BulkGetMediaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BulkGetMediaResponse.Marshal(b, m, deterministic)
}
func (m *BulkGetMediaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BulkGetMediaResponse.Merge(m, src)
}
func (m *BulkGetMediaResponse) XXX_Size() int {
	return xxx_messageInfo_BulkGetMediaResponse.Size(m)
}
func (m *BulkGetMediaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BulkGetMediaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BulkGetMediaResponse proto.InternalMessageInfo

func (m *BulkGetMediaResponse) GetMedias() []*Media {
	if m != nil {
		return m.Medias
	}
	return nil
}

func init() {
	proto.RegisterType((*Media)(nil), "media.Media")
	proto.RegisterType((*GetMediaRequest)(nil), "media.GetMediaRequest")
	proto.RegisterType((*GetMediaResponse)(nil), "media.GetMediaResponse")
	proto.RegisterType((*BulkGetMediaRequest)(nil), "media.BulkGetMediaRequest")
	proto.RegisterType((*BulkGetMediaResponse)(nil), "media.BulkGetMediaResponse")
}

func init() { proto.RegisterFile("media/media.proto", fileDescriptor_593688da247aaf8b) }

var fileDescriptor_593688da247aaf8b = []byte{
	// 319 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x4d, 0x4b, 0xfb, 0x40,
	0x10, 0xc6, 0xff, 0xf9, 0x97, 0xbe, 0x8d, 0x05, 0x75, 0x15, 0x5b, 0x5b, 0x84, 0xb2, 0xf4, 0xe0,
	0x41, 0x1a, 0xa8, 0xe2, 0x49, 0x2f, 0xbd, 0x48, 0x0f, 0x22, 0x54, 0xbd, 0x78, 0x29, 0x69, 0x33,
	0xa4, 0xd1, 0xad, 0xbb, 0xee, 0x8b, 0xd8, 0x6f, 0xe2, 0xc7, 0x95, 0xcc, 0x6e, 0x51, 0x63, 0x2f,
	0x21, 0x33, 0xf3, 0xcc, 0xf3, 0xfc, 0x92, 0x5d, 0xd8, 0x5f, 0x61, 0x9a, 0x27, 0x31, 0x3d, 0x87,
	0x4a, 0x4b, 0x2b, 0x59, 0x95, 0x0a, 0x3e, 0x80, 0xea, 0x6d, 0xf1, 0xc2, 0x7a, 0xd0, 0x54, 0x4b,
	0x69, 0xe5, 0xcc, 0x69, 0xd1, 0x89, 0xfa, 0xd1, 0x69, 0x73, 0xda, 0xa0, 0xc6, 0xa3, 0x16, 0xfc,
	0x0c, 0x76, 0x6f, 0xd0, 0x92, 0x70, 0x8a, 0x6f, 0x0e, 0x8d, 0x65, 0xc7, 0xd0, 0x20, 0x87, 0x59,
	0x9e, 0x06, 0x79, 0x9d, 0xea, 0x49, 0xca, 0x2f, 0x61, 0xef, 0x5b, 0x6d, 0x94, 0x7c, 0x35, 0xc8,
	0x38, 0xf8, 0x40, 0xd2, 0xee, 0x8c, 0x5a, 0x43, 0xcf, 0xe2, 0x45, 0x81, 0xe5, 0x19, 0x0e, 0xc6,
	0x4e, 0xbc, 0x94, 0x93, 0x7a, 0xd0, 0xdc, 0x24, 0x99, 0x4e, 0xd4, 0xaf, 0x14, 0x64, 0x21, 0xca,
	0xb0, 0x36, 0xd4, 0x9d, 0x41, 0x5d, 0x50, 0xfc, 0x27, 0x8a, 0x5a, 0x51, 0x4e, 0x52, 0x76, 0x02,
	0xe0, 0xb7, 0xec, 0x5a, 0x61, 0xa7, 0x42, 0x6b, 0xde, 0xe7, 0x61, 0xad, 0x90, 0x5f, 0xc1, 0xe1,
	0xef, 0xac, 0xc0, 0x39, 0x80, 0x1a, 0x89, 0x7c, 0x52, 0x19, 0x34, 0xcc, 0x46, 0x9f, 0x11, 0xb4,
	0xa8, 0x73, 0x8f, 0xfa, 0x3d, 0x5f, 0x20, 0xbb, 0x86, 0xc6, 0xc6, 0x8a, 0x1d, 0x85, 0x95, 0xd2,
	0x77, 0x74, 0xdb, 0x7f, 0xfa, 0x3e, 0x93, 0xff, 0x63, 0x13, 0x68, 0xfd, 0xa4, 0x61, 0xdd, 0x20,
	0xdd, 0xf2, 0x3b, 0xba, 0xbd, 0xad, 0xb3, 0x8d, 0xd5, 0xf8, 0xe2, 0x69, 0x94, 0xe5, 0x76, 0xe9,
	0xe6, 0xc3, 0x85, 0x5c, 0xc5, 0x8b, 0x44, 0x4b, 0x67, 0x50, 0x88, 0x38, 0xc9, 0x32, 0x3a, 0xf8,
	0x18, 0x3f, 0x92, 0x95, 0x12, 0x68, 0xe2, 0x4c, 0xde, 0x39, 0xeb, 0xef, 0xc4, 0xbc, 0x46, 0xb3,
	0xf3, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xfc, 0xf7, 0xc8, 0xc1, 0x29, 0x02, 0x00, 0x00,
}
