// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: inferred_input_v1/masked_listing_w_media.proto

package inferred_input_v1

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type MaskedListingWMediaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GetListing *MaskedListingWMediaRequest_GetListingGen `protobuf:"bytes,1,opt,name=get_listing,json=getListing,proto3" json:"get_listing,omitempty"`
}

func (x *MaskedListingWMediaRequest) Reset() {
	*x = MaskedListingWMediaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inferred_input_v1_masked_listing_w_media_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MaskedListingWMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaskedListingWMediaRequest) ProtoMessage() {}

func (x *MaskedListingWMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inferred_input_v1_masked_listing_w_media_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaskedListingWMediaRequest.ProtoReflect.Descriptor instead.
func (*MaskedListingWMediaRequest) Descriptor() ([]byte, []int) {
	return file_inferred_input_v1_masked_listing_w_media_proto_rawDescGZIP(), []int{0}
}

func (x *MaskedListingWMediaRequest) GetGetListing() *MaskedListingWMediaRequest_GetListingGen {
	if x != nil {
		return x.GetListing
	}
	return nil
}

type MaskedListingWMediaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Listing *MaskedListingWMediaResponse_ListingGen `protobuf:"bytes,1,opt,name=listing,proto3" json:"listing,omitempty"`
}

func (x *MaskedListingWMediaResponse) Reset() {
	*x = MaskedListingWMediaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inferred_input_v1_masked_listing_w_media_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MaskedListingWMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaskedListingWMediaResponse) ProtoMessage() {}

func (x *MaskedListingWMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inferred_input_v1_masked_listing_w_media_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaskedListingWMediaResponse.ProtoReflect.Descriptor instead.
func (*MaskedListingWMediaResponse) Descriptor() ([]byte, []int) {
	return file_inferred_input_v1_masked_listing_w_media_proto_rawDescGZIP(), []int{1}
}

func (x *MaskedListingWMediaResponse) GetListing() *MaskedListingWMediaResponse_ListingGen {
	if x != nil {
		return x.Listing
	}
	return nil
}

type MaskedListingWMediaRequest_GetListingGen struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *MaskedListingWMediaRequest_GetListingGen) Reset() {
	*x = MaskedListingWMediaRequest_GetListingGen{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inferred_input_v1_masked_listing_w_media_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MaskedListingWMediaRequest_GetListingGen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaskedListingWMediaRequest_GetListingGen) ProtoMessage() {}

func (x *MaskedListingWMediaRequest_GetListingGen) ProtoReflect() protoreflect.Message {
	mi := &file_inferred_input_v1_masked_listing_w_media_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaskedListingWMediaRequest_GetListingGen.ProtoReflect.Descriptor instead.
func (*MaskedListingWMediaRequest_GetListingGen) Descriptor() ([]byte, []int) {
	return file_inferred_input_v1_masked_listing_w_media_proto_rawDescGZIP(), []int{0, 0}
}

func (x *MaskedListingWMediaRequest_GetListingGen) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type MaskedListingWMediaResponse_ListingGen struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title       string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	PhotoUrl    string `protobuf:"bytes,3,opt,name=photo_url,json=photoUrl,proto3" json:"photo_url,omitempty"`
}

func (x *MaskedListingWMediaResponse_ListingGen) Reset() {
	*x = MaskedListingWMediaResponse_ListingGen{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inferred_input_v1_masked_listing_w_media_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MaskedListingWMediaResponse_ListingGen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaskedListingWMediaResponse_ListingGen) ProtoMessage() {}

func (x *MaskedListingWMediaResponse_ListingGen) ProtoReflect() protoreflect.Message {
	mi := &file_inferred_input_v1_masked_listing_w_media_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaskedListingWMediaResponse_ListingGen.ProtoReflect.Descriptor instead.
func (*MaskedListingWMediaResponse_ListingGen) Descriptor() ([]byte, []int) {
	return file_inferred_input_v1_masked_listing_w_media_proto_rawDescGZIP(), []int{1, 0}
}

func (x *MaskedListingWMediaResponse_ListingGen) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MaskedListingWMediaResponse_ListingGen) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MaskedListingWMediaResponse_ListingGen) GetPhotoUrl() string {
	if x != nil {
		return x.PhotoUrl
	}
	return ""
}

var File_inferred_input_v1_masked_listing_w_media_proto protoreflect.FileDescriptor

var file_inferred_input_v1_masked_listing_w_media_proto_rawDesc = []byte{
	0x0a, 0x2e, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x72, 0x65, 0x64, 0x5f, 0x69, 0x6e, 0x70, 0x75, 0x74,
	0x5f, 0x76, 0x31, 0x2f, 0x6d, 0x61, 0x73, 0x6b, 0x65, 0x64, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x69,
	0x6e, 0x67, 0x5f, 0x77, 0x5f, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x11, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x72, 0x65, 0x64, 0x5f, 0x69, 0x6e, 0x70, 0x75, 0x74,
	0x5f, 0x76, 0x31, 0x22, 0x9b, 0x01, 0x0a, 0x1a, 0x4d, 0x61, 0x73, 0x6b, 0x65, 0x64, 0x4c, 0x69,
	0x73, 0x74, 0x69, 0x6e, 0x67, 0x57, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x5c, 0x0a, 0x0b, 0x67, 0x65, 0x74, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x6e,
	0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3b, 0x2e, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x72,
	0x65, 0x64, 0x5f, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x5f, 0x76, 0x31, 0x2e, 0x4d, 0x61, 0x73, 0x6b,
	0x65, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x57, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e,
	0x67, 0x47, 0x65, 0x6e, 0x52, 0x0a, 0x67, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67,
	0x1a, 0x1f, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x47, 0x65,
	0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x22, 0xd5, 0x01, 0x0a, 0x1b, 0x4d, 0x61, 0x73, 0x6b, 0x65, 0x64, 0x4c, 0x69, 0x73, 0x74,
	0x69, 0x6e, 0x67, 0x57, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x53, 0x0a, 0x07, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x39, 0x2e, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x72, 0x65, 0x64, 0x5f, 0x69, 0x6e,
	0x70, 0x75, 0x74, 0x5f, 0x76, 0x31, 0x2e, 0x4d, 0x61, 0x73, 0x6b, 0x65, 0x64, 0x4c, 0x69, 0x73,
	0x74, 0x69, 0x6e, 0x67, 0x57, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x47, 0x65, 0x6e, 0x52, 0x07, 0x6c,
	0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x1a, 0x61, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e,
	0x67, 0x47, 0x65, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09,
	0x70, 0x68, 0x6f, 0x74, 0x6f, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x55, 0x72, 0x6c, 0x32, 0x98, 0x01, 0x0a, 0x1a, 0x4d, 0x61,
	0x73, 0x6b, 0x65, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x57, 0x4d, 0x65, 0x64, 0x69,
	0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x7a, 0x0a, 0x19, 0x49, 0x6e, 0x76, 0x6f,
	0x6b, 0x65, 0x4d, 0x61, 0x73, 0x6b, 0x65, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x57,
	0x4d, 0x65, 0x64, 0x69, 0x61, 0x12, 0x2d, 0x2e, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x72, 0x65, 0x64,
	0x5f, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x5f, 0x76, 0x31, 0x2e, 0x4d, 0x61, 0x73, 0x6b, 0x65, 0x64,
	0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x57, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x72, 0x65, 0x64, 0x5f,
	0x69, 0x6e, 0x70, 0x75, 0x74, 0x5f, 0x76, 0x31, 0x2e, 0x4d, 0x61, 0x73, 0x6b, 0x65, 0x64, 0x4c,
	0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x57, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x40, 0x5a, 0x3e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x63, 0x61, 0x72, 0x6f, 0x75, 0x73, 0x65, 0x6c, 0x6c, 0x2f, 0x61, 0x67, 0x67,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2f, 0x67,
	0x6f, 0x4f, 0x75, 0x74, 0x2f, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x72, 0x65, 0x64, 0x5f, 0x69, 0x6e,
	0x70, 0x75, 0x74, 0x5f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_inferred_input_v1_masked_listing_w_media_proto_rawDescOnce sync.Once
	file_inferred_input_v1_masked_listing_w_media_proto_rawDescData = file_inferred_input_v1_masked_listing_w_media_proto_rawDesc
)

func file_inferred_input_v1_masked_listing_w_media_proto_rawDescGZIP() []byte {
	file_inferred_input_v1_masked_listing_w_media_proto_rawDescOnce.Do(func() {
		file_inferred_input_v1_masked_listing_w_media_proto_rawDescData = protoimpl.X.CompressGZIP(file_inferred_input_v1_masked_listing_w_media_proto_rawDescData)
	})
	return file_inferred_input_v1_masked_listing_w_media_proto_rawDescData
}

var file_inferred_input_v1_masked_listing_w_media_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_inferred_input_v1_masked_listing_w_media_proto_goTypes = []interface{}{
	(*MaskedListingWMediaRequest)(nil),               // 0: inferred_input_v1.MaskedListingWMediaRequest
	(*MaskedListingWMediaResponse)(nil),              // 1: inferred_input_v1.MaskedListingWMediaResponse
	(*MaskedListingWMediaRequest_GetListingGen)(nil), // 2: inferred_input_v1.MaskedListingWMediaRequest.GetListingGen
	(*MaskedListingWMediaResponse_ListingGen)(nil),   // 3: inferred_input_v1.MaskedListingWMediaResponse.ListingGen
}
var file_inferred_input_v1_masked_listing_w_media_proto_depIdxs = []int32{
	2, // 0: inferred_input_v1.MaskedListingWMediaRequest.get_listing:type_name -> inferred_input_v1.MaskedListingWMediaRequest.GetListingGen
	3, // 1: inferred_input_v1.MaskedListingWMediaResponse.listing:type_name -> inferred_input_v1.MaskedListingWMediaResponse.ListingGen
	0, // 2: inferred_input_v1.MaskedListingWMediaService.InvokeMaskedListingWMedia:input_type -> inferred_input_v1.MaskedListingWMediaRequest
	1, // 3: inferred_input_v1.MaskedListingWMediaService.InvokeMaskedListingWMedia:output_type -> inferred_input_v1.MaskedListingWMediaResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_inferred_input_v1_masked_listing_w_media_proto_init() }
func file_inferred_input_v1_masked_listing_w_media_proto_init() {
	if File_inferred_input_v1_masked_listing_w_media_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_inferred_input_v1_masked_listing_w_media_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MaskedListingWMediaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inferred_input_v1_masked_listing_w_media_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MaskedListingWMediaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inferred_input_v1_masked_listing_w_media_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MaskedListingWMediaRequest_GetListingGen); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inferred_input_v1_masked_listing_w_media_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MaskedListingWMediaResponse_ListingGen); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_inferred_input_v1_masked_listing_w_media_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inferred_input_v1_masked_listing_w_media_proto_goTypes,
		DependencyIndexes: file_inferred_input_v1_masked_listing_w_media_proto_depIdxs,
		MessageInfos:      file_inferred_input_v1_masked_listing_w_media_proto_msgTypes,
	}.Build()
	File_inferred_input_v1_masked_listing_w_media_proto = out.File
	file_inferred_input_v1_masked_listing_w_media_proto_rawDesc = nil
	file_inferred_input_v1_masked_listing_w_media_proto_goTypes = nil
	file_inferred_input_v1_masked_listing_w_media_proto_depIdxs = nil
}
