// Code generated by protoc-gen-go. DO NOT EDIT.
// source: listing/listing.proto

package listing

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Status int32

const (
	Status_UNKNOWN Status = 0
	Status_LISTED  Status = 1
	Status_SOLD    Status = 2
)

var Status_name = map[int32]string{
	0: "UNKNOWN",
	1: "LISTED",
	2: "SOLD",
}

var Status_value = map[string]int32{
	"UNKNOWN": 0,
	"LISTED":  1,
	"SOLD":    2,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f66bcb41390a3769, []int{0}
}

type Listing struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	MediaId              string   `protobuf:"bytes,4,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	Status               Status   `protobuf:"varint,5,opt,name=status,proto3,enum=listing.Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Listing) Reset()         { *m = Listing{} }
func (m *Listing) String() string { return proto.CompactTextString(m) }
func (*Listing) ProtoMessage()    {}
func (*Listing) Descriptor() ([]byte, []int) {
	return fileDescriptor_f66bcb41390a3769, []int{0}
}

func (m *Listing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Listing.Unmarshal(m, b)
}
func (m *Listing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Listing.Marshal(b, m, deterministic)
}
func (m *Listing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Listing.Merge(m, src)
}
func (m *Listing) XXX_Size() int {
	return xxx_messageInfo_Listing.Size(m)
}
func (m *Listing) XXX_DiscardUnknown() {
	xxx_messageInfo_Listing.DiscardUnknown(m)
}

var xxx_messageInfo_Listing proto.InternalMessageInfo

func (m *Listing) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Listing) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Listing) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Listing) GetMediaId() string {
	if m != nil {
		return m.MediaId
	}
	return ""
}

func (m *Listing) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_UNKNOWN
}

type BulkGetListingsRequest struct {
	ListingIds           []string `protobuf:"bytes,1,rep,name=listing_ids,json=listingIds,proto3" json:"listing_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BulkGetListingsRequest) Reset()         { *m = BulkGetListingsRequest{} }
func (m *BulkGetListingsRequest) String() string { return proto.CompactTextString(m) }
func (*BulkGetListingsRequest) ProtoMessage()    {}
func (*BulkGetListingsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f66bcb41390a3769, []int{1}
}

func (m *BulkGetListingsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BulkGetListingsRequest.Unmarshal(m, b)
}
func (m *BulkGetListingsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BulkGetListingsRequest.Marshal(b, m, deterministic)
}
func (m *BulkGetListingsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BulkGetListingsRequest.Merge(m, src)
}
func (m *BulkGetListingsRequest) XXX_Size() int {
	return xxx_messageInfo_BulkGetListingsRequest.Size(m)
}
func (m *BulkGetListingsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BulkGetListingsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BulkGetListingsRequest proto.InternalMessageInfo

func (m *BulkGetListingsRequest) GetListingIds() []string {
	if m != nil {
		return m.ListingIds
	}
	return nil
}

type BulkGetListingsResponse struct {
	Listings             []*Listing `protobuf:"bytes,1,rep,name=listings,proto3" json:"listings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *BulkGetListingsResponse) Reset()         { *m = BulkGetListingsResponse{} }
func (m *BulkGetListingsResponse) String() string { return proto.CompactTextString(m) }
func (*BulkGetListingsResponse) ProtoMessage()    {}
func (*BulkGetListingsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f66bcb41390a3769, []int{2}
}

func (m *BulkGetListingsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BulkGetListingsResponse.Unmarshal(m, b)
}
func (m *BulkGetListingsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BulkGetListingsResponse.Marshal(b, m, deterministic)
}
func (m *BulkGetListingsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BulkGetListingsResponse.Merge(m, src)
}
func (m *BulkGetListingsResponse) XXX_Size() int {
	return xxx_messageInfo_BulkGetListingsResponse.Size(m)
}
func (m *BulkGetListingsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BulkGetListingsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BulkGetListingsResponse proto.InternalMessageInfo

func (m *BulkGetListingsResponse) GetListings() []*Listing {
	if m != nil {
		return m.Listings
	}
	return nil
}

type GetListingRequest struct {
	ListingId            string   `protobuf:"bytes,1,opt,name=listing_id,json=listingId,proto3" json:"listing_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetListingRequest) Reset()         { *m = GetListingRequest{} }
func (m *GetListingRequest) String() string { return proto.CompactTextString(m) }
func (*GetListingRequest) ProtoMessage()    {}
func (*GetListingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f66bcb41390a3769, []int{3}
}

func (m *GetListingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListingRequest.Unmarshal(m, b)
}
func (m *GetListingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListingRequest.Marshal(b, m, deterministic)
}
func (m *GetListingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListingRequest.Merge(m, src)
}
func (m *GetListingRequest) XXX_Size() int {
	return xxx_messageInfo_GetListingRequest.Size(m)
}
func (m *GetListingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetListingRequest proto.InternalMessageInfo

func (m *GetListingRequest) GetListingId() string {
	if m != nil {
		return m.ListingId
	}
	return ""
}

type GetListingResponse struct {
	Listing              *Listing `protobuf:"bytes,1,opt,name=listing,proto3" json:"listing,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetListingResponse) Reset()         { *m = GetListingResponse{} }
func (m *GetListingResponse) String() string { return proto.CompactTextString(m) }
func (*GetListingResponse) ProtoMessage()    {}
func (*GetListingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f66bcb41390a3769, []int{4}
}

func (m *GetListingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListingResponse.Unmarshal(m, b)
}
func (m *GetListingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListingResponse.Marshal(b, m, deterministic)
}
func (m *GetListingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListingResponse.Merge(m, src)
}
func (m *GetListingResponse) XXX_Size() int {
	return xxx_messageInfo_GetListingResponse.Size(m)
}
func (m *GetListingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetListingResponse proto.InternalMessageInfo

func (m *GetListingResponse) GetListing() *Listing {
	if m != nil {
		return m.Listing
	}
	return nil
}

func init() {
	proto.RegisterEnum("listing.Status", Status_name, Status_value)
	proto.RegisterType((*Listing)(nil), "listing.Listing")
	proto.RegisterType((*BulkGetListingsRequest)(nil), "listing.BulkGetListingsRequest")
	proto.RegisterType((*BulkGetListingsResponse)(nil), "listing.BulkGetListingsResponse")
	proto.RegisterType((*GetListingRequest)(nil), "listing.GetListingRequest")
	proto.RegisterType((*GetListingResponse)(nil), "listing.GetListingResponse")
}

func init() { proto.RegisterFile("listing/listing.proto", fileDescriptor_f66bcb41390a3769) }

var fileDescriptor_f66bcb41390a3769 = []byte{
	// 386 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x5d, 0x8b, 0xda, 0x40,
	0x14, 0x35, 0x51, 0x93, 0x78, 0x03, 0x9a, 0x5e, 0xfa, 0x91, 0x5a, 0x8a, 0x21, 0x2f, 0x15, 0x5b,
	0x0c, 0xa4, 0xa5, 0xd0, 0xb7, 0x22, 0x16, 0x91, 0x8a, 0x42, 0xec, 0x07, 0xf4, 0x45, 0xa2, 0x33,
	0xa4, 0xc3, 0x46, 0x93, 0x75, 0x26, 0xb0, 0x7f, 0x64, 0x7f, 0xc5, 0xfe, 0xc9, 0x85, 0xc9, 0x24,
	0xca, 0xea, 0x3e, 0x25, 0xf7, 0x9e, 0x73, 0xe6, 0x9c, 0x39, 0x0c, 0xbc, 0x4a, 0x19, 0x17, 0xec,
	0x90, 0x04, 0xea, 0x3b, 0xce, 0x8f, 0x99, 0xc8, 0xd0, 0x54, 0xa3, 0x7f, 0xaf, 0x81, 0xb9, 0x28,
	0xff, 0xb1, 0x0b, 0x3a, 0x23, 0xae, 0xe6, 0x69, 0xc3, 0x4e, 0xa4, 0x33, 0x82, 0x2f, 0xa1, 0x2d,
	0x98, 0x48, 0xa9, 0xab, 0xcb, 0x55, 0x39, 0xa0, 0x07, 0x36, 0xa1, 0x7c, 0x77, 0x64, 0xb9, 0x60,
	0xd9, 0xc1, 0x6d, 0x4a, 0xec, 0x7c, 0x85, 0x6f, 0xc1, 0xda, 0x53, 0xc2, 0xe2, 0x0d, 0x23, 0x6e,
	0x4b, 0xc2, 0xa6, 0x9c, 0xe7, 0x04, 0x3f, 0x80, 0xc1, 0x45, 0x2c, 0x0a, 0xee, 0xb6, 0x3d, 0x6d,
	0xd8, 0x0d, 0x7b, 0xe3, 0x2a, 0xd7, 0x5a, 0xae, 0x23, 0x05, 0xfb, 0xdf, 0xe0, 0xf5, 0xa4, 0x48,
	0x6f, 0x66, 0x54, 0xa8, 0x74, 0x3c, 0xa2, 0xb7, 0x05, 0xe5, 0x02, 0x07, 0x60, 0x2b, 0xcd, 0x86,
	0x11, 0xee, 0x6a, 0x5e, 0x73, 0xd8, 0x89, 0x40, 0xad, 0xe6, 0x84, 0xfb, 0x33, 0x78, 0x73, 0x21,
	0xe5, 0x79, 0x76, 0xe0, 0x14, 0x3f, 0x81, 0xa5, 0x88, 0xa5, 0xd0, 0x0e, 0x9d, 0x3a, 0x80, 0x22,
	0x47, 0x35, 0xc3, 0x0f, 0xe1, 0xc5, 0xe9, 0x90, 0xca, 0xfe, 0x3d, 0xc0, 0xc9, 0x5e, 0x95, 0xd5,
	0xa9, 0xdd, 0xfd, 0xef, 0x80, 0xe7, 0x1a, 0xe5, 0x3b, 0x82, 0xaa, 0x70, 0xa9, 0xb8, 0x66, 0x5b,
	0x11, 0x46, 0x1f, 0xc1, 0x28, 0xbb, 0x40, 0x1b, 0xcc, 0xdf, 0xcb, 0x9f, 0xcb, 0xd5, 0xdf, 0xa5,
	0xd3, 0x40, 0x00, 0x63, 0x31, 0x5f, 0xff, 0xfa, 0x31, 0x75, 0x34, 0xb4, 0xa0, 0xb5, 0x5e, 0x2d,
	0xa6, 0x8e, 0x1e, 0x3e, 0x68, 0x60, 0x55, 0xb7, 0xc4, 0x3f, 0xd0, 0x7b, 0x72, 0x71, 0x1c, 0xd4,
	0x3e, 0xd7, 0xdb, 0xec, 0x7b, 0xcf, 0x13, 0xca, 0xec, 0x7e, 0x03, 0x67, 0x00, 0x27, 0x00, 0xfb,
	0xb5, 0xe2, 0xa2, 0x9c, 0xfe, 0xbb, 0xab, 0x58, 0x75, 0xd0, 0xe4, 0xeb, 0xbf, 0x2f, 0x09, 0x13,
	0xff, 0x8b, 0xed, 0x78, 0x97, 0xed, 0x83, 0x5d, 0x7c, 0xcc, 0x0a, 0x4e, 0xd3, 0x34, 0x88, 0x93,
	0x44, 0x3e, 0xcb, 0x80, 0xde, 0xc5, 0xfb, 0x3c, 0xa5, 0x3c, 0x48, 0xb2, 0x55, 0x21, 0xaa, 0x37,
	0xbb, 0x35, 0x24, 0xfa, 0xf9, 0x31, 0x00, 0x00, 0xff, 0xff, 0xec, 0xbd, 0x41, 0x81, 0xcd, 0x02,
	0x00, 0x00,
}
