// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package listing

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ListingsClient is the client API for Listings service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ListingsClient interface {
	BulkGetListings(ctx context.Context, in *BulkGetListingsRequest, opts ...grpc.CallOption) (*BulkGetListingsResponse, error)
	GetListing(ctx context.Context, in *GetListingRequest, opts ...grpc.CallOption) (*GetListingResponse, error)
}

type listingsClient struct {
	cc grpc.ClientConnInterface
}

func NewListingsClient(cc grpc.ClientConnInterface) ListingsClient {
	return &listingsClient{cc}
}

func (c *listingsClient) BulkGetListings(ctx context.Context, in *BulkGetListingsRequest, opts ...grpc.CallOption) (*BulkGetListingsResponse, error) {
	out := new(BulkGetListingsResponse)
	err := c.cc.Invoke(ctx, "/listing.Listings/BulkGetListings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *listingsClient) GetListing(ctx context.Context, in *GetListingRequest, opts ...grpc.CallOption) (*GetListingResponse, error) {
	out := new(GetListingResponse)
	err := c.cc.Invoke(ctx, "/listing.Listings/GetListing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ListingsServer is the server API for Listings service.
// All implementations must embed UnimplementedListingsServer
// for forward compatibility
type ListingsServer interface {
	BulkGetListings(context.Context, *BulkGetListingsRequest) (*BulkGetListingsResponse, error)
	GetListing(context.Context, *GetListingRequest) (*GetListingResponse, error)
	mustEmbedUnimplementedListingsServer()
}

// UnimplementedListingsServer must be embedded to have forward compatible implementations.
type UnimplementedListingsServer struct {
}

func (*UnimplementedListingsServer) BulkGetListings(context.Context, *BulkGetListingsRequest) (*BulkGetListingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BulkGetListings not implemented")
}
func (*UnimplementedListingsServer) GetListing(context.Context, *GetListingRequest) (*GetListingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetListing not implemented")
}
func (*UnimplementedListingsServer) mustEmbedUnimplementedListingsServer() {}

func RegisterListingsServer(s *grpc.Server, srv ListingsServer) {
	s.RegisterService(&_Listings_serviceDesc, srv)
}

func _Listings_BulkGetListings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BulkGetListingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListingsServer).BulkGetListings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/listing.Listings/BulkGetListings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListingsServer).BulkGetListings(ctx, req.(*BulkGetListingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Listings_GetListing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListingsServer).GetListing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/listing.Listings/GetListing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListingsServer).GetListing(ctx, req.(*GetListingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Listings_serviceDesc = grpc.ServiceDesc{
	ServiceName: "listing.Listings",
	HandlerType: (*ListingsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BulkGetListings",
			Handler:    _Listings_BulkGetListings_Handler,
		},
		{
			MethodName: "GetListing",
			Handler:    _Listings_GetListing_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "listing/listing.proto",
}
