// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wallet/wallet.proto

package wallet

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserWallet struct {
	CoinBalance          int64    `protobuf:"varint,1,opt,name=coin_balance,json=coinBalance,proto3" json:"coin_balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserWallet) Reset()         { *m = UserWallet{} }
func (m *UserWallet) String() string { return proto.CompactTextString(m) }
func (*UserWallet) ProtoMessage()    {}
func (*UserWallet) Descriptor() ([]byte, []int) {
	return fileDescriptor_4aabd033bbdba6c1, []int{0}
}

func (m *UserWallet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserWallet.Unmarshal(m, b)
}
func (m *UserWallet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserWallet.Marshal(b, m, deterministic)
}
func (m *UserWallet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserWallet.Merge(m, src)
}
func (m *UserWallet) XXX_Size() int {
	return xxx_messageInfo_UserWallet.Size(m)
}
func (m *UserWallet) XXX_DiscardUnknown() {
	xxx_messageInfo_UserWallet.DiscardUnknown(m)
}

var xxx_messageInfo_UserWallet proto.InternalMessageInfo

func (m *UserWallet) GetCoinBalance() int64 {
	if m != nil {
		return m.CoinBalance
	}
	return 0
}

type GetUserWalletRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserWalletRequest) Reset()         { *m = GetUserWalletRequest{} }
func (m *GetUserWalletRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserWalletRequest) ProtoMessage()    {}
func (*GetUserWalletRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4aabd033bbdba6c1, []int{1}
}

func (m *GetUserWalletRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserWalletRequest.Unmarshal(m, b)
}
func (m *GetUserWalletRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserWalletRequest.Marshal(b, m, deterministic)
}
func (m *GetUserWalletRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserWalletRequest.Merge(m, src)
}
func (m *GetUserWalletRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserWalletRequest.Size(m)
}
func (m *GetUserWalletRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserWalletRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserWalletRequest proto.InternalMessageInfo

func (m *GetUserWalletRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type GetUserWalletResponse struct {
	UserWallet           *UserWallet `protobuf:"bytes,1,opt,name=user_wallet,json=userWallet,proto3" json:"user_wallet,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetUserWalletResponse) Reset()         { *m = GetUserWalletResponse{} }
func (m *GetUserWalletResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserWalletResponse) ProtoMessage()    {}
func (*GetUserWalletResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4aabd033bbdba6c1, []int{2}
}

func (m *GetUserWalletResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserWalletResponse.Unmarshal(m, b)
}
func (m *GetUserWalletResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserWalletResponse.Marshal(b, m, deterministic)
}
func (m *GetUserWalletResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserWalletResponse.Merge(m, src)
}
func (m *GetUserWalletResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserWalletResponse.Size(m)
}
func (m *GetUserWalletResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserWalletResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserWalletResponse proto.InternalMessageInfo

func (m *GetUserWalletResponse) GetUserWallet() *UserWallet {
	if m != nil {
		return m.UserWallet
	}
	return nil
}

func init() {
	proto.RegisterType((*UserWallet)(nil), "wallet.UserWallet")
	proto.RegisterType((*GetUserWalletRequest)(nil), "wallet.GetUserWalletRequest")
	proto.RegisterType((*GetUserWalletResponse)(nil), "wallet.GetUserWalletResponse")
}

func init() { proto.RegisterFile("wallet/wallet.proto", fileDescriptor_4aabd033bbdba6c1) }

var fileDescriptor_4aabd033bbdba6c1 = []byte{
	// 230 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xcb, 0x4a, 0xc5, 0x30,
	0x10, 0x86, 0x3d, 0x08, 0x11, 0xa7, 0xba, 0x89, 0x8a, 0x22, 0x0a, 0x9a, 0x95, 0xab, 0x06, 0x4e,
	0xf1, 0x05, 0xba, 0x11, 0x41, 0x14, 0x0a, 0xa2, 0xb8, 0x29, 0x69, 0x3a, 0xc4, 0x42, 0xda, 0xd4,
	0x5c, 0xd0, 0xc7, 0x97, 0x26, 0xad, 0x37, 0x3c, 0xab, 0xe4, 0x9f, 0xe1, 0x1b, 0x3e, 0x7e, 0x38,
	0x78, 0x17, 0x5a, 0xa3, 0xe7, 0xe9, 0xc9, 0x47, 0x6b, 0xbc, 0xa1, 0x24, 0x25, 0xc6, 0x01, 0x1e,
	0x1d, 0xda, 0xa7, 0x98, 0xe8, 0x25, 0xec, 0x49, 0xd3, 0x0d, 0x75, 0x23, 0xb4, 0x18, 0x24, 0x9e,
	0xac, 0x2e, 0x56, 0x57, 0xdb, 0x55, 0x36, 0xcd, 0xca, 0x34, 0x62, 0x1c, 0x0e, 0x6f, 0xd0, 0x7f,
	0x33, 0x15, 0xbe, 0x05, 0x74, 0x9e, 0x1e, 0xc3, 0x4e, 0x70, 0x68, 0xeb, 0xae, 0x8d, 0xd4, 0x6e,
	0x45, 0xa6, 0x78, 0xdb, 0xb2, 0x3b, 0x38, 0xfa, 0x03, 0xb8, 0xd1, 0x0c, 0x0e, 0x69, 0x01, 0x59,
	0x24, 0x92, 0x49, 0xa4, 0xb2, 0x35, 0xcd, 0x67, 0xcd, 0x1f, 0x00, 0x84, 0xaf, 0xff, 0xfa, 0x19,
	0xc8, 0xec, 0x7a, 0x0f, 0xfb, 0xbf, 0xee, 0xd2, 0xb3, 0x05, 0xfd, 0xcf, 0xef, 0xf4, 0x7c, 0xc3,
	0x36, 0xc9, 0xb0, 0xad, 0xf2, 0xfa, 0xa5, 0x50, 0x9d, 0x7f, 0x0d, 0x4d, 0x2e, 0x4d, 0xcf, 0xa5,
	0xb0, 0x26, 0x38, 0xd4, 0x9a, 0x0b, 0xa5, 0x62, 0x65, 0x1c, 0x3f, 0x44, 0x3f, 0x6a, 0x74, 0x5c,
	0x99, 0x87, 0xb0, 0xd4, 0xd9, 0x90, 0xb8, 0x2c, 0x3e, 0x03, 0x00, 0x00, 0xff, 0xff, 0x88, 0xd4,
	0x69, 0xe9, 0x66, 0x01, 0x00, 0x00,
}
